### ISSUE TITLE
Custom colors.

### ISSUE THREAD

**Issue by steliosph** [Serhioromano/bootstrap-calendar#146]
Instead of limiting the amount of colors that can be set in the events to the event-\* perhaps we can also give the ability to add user defined colors.

Something like adding into the json file another parameter color that will define either the hex color or the color name.

**Comment by ShayMu** [comment]
Hi, I'm just starting to use the bootstrap-calendar and I also want to do custom events colors and your method works, but how can I change the hover color of events to resemble the selected custom color? is it possible?
