### ISSUE TITLE
week view: each event in different row

### ISSUE THREAD

**Issue by bart6114** [Serhioromano/bootstrap-calendar#163]
In week view every event - even single day events - are pushed in seperate rows. Is there an easy way to get around this? In the example below there are a number of single-day events. I would like to display these at the top of the day.

![image](https://f.cloud.github.com/assets/1965492/1396933/a933f498-3c79-11e3-8f2b-1bea09a96fbf.png)

Thanks

**Comment by deepikaguptamobikasa** [comment]
i am facing issue for daywise. events are not showing on relevant time. Please help me out asap.
Thanks

**Comment by cablegunmaster** [comment]
Please make a new issue for your problem as its not related to this issue.
