### ISSUE TITLE
Can't get quick setup working

### ISSUE THREAD

**Issue by nop33** [Serhioromano/bootstrap-calendar#166]
Hello!
I am trying to setup bootstrap-calendar, but I am having some difficulties. I used the command 'bower install bootstrap-calendar' to download the dependences and I created a test index file which looks like this:
![screen shot 2013-10-28 at 1 19 13 am](https://f.cloud.github.com/assets/1579899/1416765/9d786270-3f66-11e3-8f96-3dc07e5f2ee1.png)
Opening index.html with a browser, gives an empty page.
Thanks in advance,
Ilias

**Comment by xuanthang87** [comment]
Thanks @natoshi !

**Comment by cvcv01** [comment]
Seems like I did everything right, but get:

    TypeError: this.options.templates[this.options.view] is not a function

and get a blank screen, with the following code:

	<!DOCTYPE html>
	<html>
	<head>
		<link rel="stylesheet" href="http://000.000.000.000/project/public/css/app.css" >
		<link rel="stylesheet" href="http://000.000.000.000/project/public/bootstrap-calendar/css/calendar.css">
	</head>
	<body>

		<div id="calendar"></div>	

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
		<script type="text/javascript" src="http://000.000.000.000/project/public/underscore/underscore-min.js"></script>
		<script type="text/javascript" src="http://000.000.000.000/project/public/bootstrap-calendar/js/calendar.js"></script>

		<script type="text/javascript">
			var calendar = $('#calendar').calendar({
			events_source: [
				{
					"id": 293,
					"title": "Event 1",
					"url": "http://example.com",
					"class": "event-important",
					"start": 12039485678000, // Milliseconds
					"end": 1234576967000 // Milliseconds
				}
			],
			tmpl_path: "http://000.000.000.000/project/public/bootstrap-calendar/tmpls"
			});
		</script>

	</body>
	</html>

I'm sure i'm close to getting it right, just not sure what's missing. Thanks @Serhioromano for your excellent work. Many apps need a nice responsive calendar.

**Comment by eleazan** [comment]
Check http://000.000.000.000/project/public/bootstrap-calendar/tmpls is accesible...

Seems that not load the templates

**Comment by cvcv01** [comment]
@eleazan True. You're right. tmpl_path must work, otherwise, nothing get's loaded. Since i'm using a framework, I couldn't figure out which path to use in there. I got it once I tried (project structure being /project/public/bootstrap-calendar/tmpls) : 

     tmpl_path: "./bootstrap-calendar/tmpls/"

instead of

    tmpl_path: "http://000.000.000.000/project/public/bootstrap-calendar/tmpls"

Thanks!

**Comment by kafiyakafi** [comment]
guys, i got an issue about converting date into millisecond. your millisecond example  

                         id": "532",
			"title": "This is inverse event",
			"url": "http://www.example.com/",
			"class": "event-inverse",
			"start": "1364407200000",
			"end":   "1364493686400"

i just convert the start and end but the result make me confuse. for the start : 1925-11-17 07:11:12
and for the "end" : 1928-08-14 07:11:12.
depends on it, i think there's something wrong. can you help me?
