### ISSUE TITLE
How can I create a clickhandler for the event-items?

### ISSUE THREAD

**Issue by KiddingMe42** [Serhioromano/bootstrap-calendar#200]
I want to create a clickhandler in javascript/jQuery for the event-items. So that I can toggle options to edit this entry. How could I do that?

**Comment by frankV** [comment]
@KiddingMe42 did you ever get this to work?

**Comment by eleazan** [comment]
No... you can do that in two ways...

1) Modifying calendar.js:
Here: https://github.com/Serhioromano/bootstrap-calendar/blob/master/js/calendar.js#L1209-L1218 You can add (inside the timeout) whatever you want with a.event-item 

2) Modifying templates:
https://github.com/Serhioromano/bootstrap-calendar/blob/master/tmpls/events-list.html

You can add here some js functions on the "onclick" of the <a> 


But... that can be a new option (get a callback after the event list is showed)

**Comment by OwenCalzadilla** [comment]
I got the jquery event callback working, it only required a small change, instead of defining the $('a.event-item') as the event data define it this way $(document).click('a.event-item'), this will bind the click callback to all te events that are still not present in the view.

```javascript
var calendar = $('#calendar').calendar({
    events_source: [], 
    onAfterViewLoad: function (view) {
        $(document).click('a.event-item', function(e){
            e.preventDefault();
            e.stopPropogation();
            var id = $(this).data('event-id');
        });
    }
});
```
