### ISSUE TITLE
Badges and broken layout in year view

### ISSUE THREAD

**Issue by optimusprimed** [Serhioromano/bootstrap-calendar#207]
Hi,

We downloaded the latest version from Git, and added our own custom events for January, May and September. For all other months, when hovering over a month, the gray background does not fill the whole cell, and the red badges in Jan/May/Sept are aligned to the left-most margin. This is reproducable on the demo code and is not a CSS conflict.

Please can this be fixed as we'd love to use the calendar on a live website.

Thank you for this great calendar.

**Comment by eleazan** [comment]
No responso, so i close... >_<
