### ISSUE TITLE
Week view events

### ISSUE THREAD

**Issue by iulianmihai** [Serhioromano/bootstrap-calendar#255]
I have a particular case where all my events are only one day long and I was wondering if there is any way to display the events in week view  in the same line versus cascade? If there is not such an option can you please guide me what should I change to do this like an option for one day events? Thanks.

**Comment by ErathiaChia** [comment]
Hi @iulianmihai, 
I tried editing your week-days.html template, is this how it suppose to look like?
![isthishowyourcodelooklike](https://cloud.githubusercontent.com/assets/13035288/8517547/a8c4b93e-23f4-11e5-8cb1-a1e82538b5fb.png)

**Comment by iulianmihai** [comment]
@ErathiaChia yes, looks good like that.

**Comment by iulianmihai** [comment]
@ErathiaChia this is how looks in my app
![screen shot 2015-07-06 at 10 03 36 am](https://cloud.githubusercontent.com/assets/1228570/8524020/6bff7422-23c6-11e5-8993-bc0c525cb763.png)
