### ISSUE TITLE
Multiple event listing on single day

### ISSUE THREAD

**Issue by jamesmbyrne** [Serhioromano/bootstrap-calendar#273]
Hi, Congrats on a great calendar. I've a question though, when you have more than one event on a day each successive event appears to the right of the previous, this look OK on a computer, but on a mobile device the second event appears at the bottom of the calendar as there is no room to appear to the right. Is there a tweak to make events appear immediately below each other?

**Comment by ErathiaChia** [comment]
I think what he meant was, all the event was on one row by itself. Is there anyway to left align everything?

![whatishappening](https://cloud.githubusercontent.com/assets/13035288/8517199/7e011aac-23f0-11e5-96fe-464dfd3268ff.png)
Into something like this?
![whatiwanttodo](https://cloud.githubusercontent.com/assets/13035288/8517207/a13d54ae-23f0-11e5-9857-20b636acd229.png)

Ecytchia@gmail.com

**Comment by markinfurkin** [comment]
i have same problem of <b>ErathiaChia</b>, is possible to align events to the left?

**Comment by eleazan** [comment]
Play with css...

Something like

````
#cal-day-box .day-highlight {
  position: absolute;
  /*width: 94.5%;*/
  min-height: 30px;	
}

#cal-day-box .day-event {
	max-width: none;
	width: 94.5%;	
}
````

Should be nice...

**Comment by markinfurkin** [comment]
<code> 
#cal-day-box .day-highlight {
position: absolute;
}
</code>
its worked fine for me, thank you!

**Comment by Serhioromano** [comment]
As @crankharder nave already mentioned it is not a trivial task. And I do not think it is worth doing with what we have now.  I mean with all those underscore, jquery dependencies. The purpose of this calendar was to be light and simplistic. I have long going dream to create new one (based on this one) but built on web components standards so it could be used without dependencies with any modern framework like Aurelia, Angular, ..

SO this feature is for the future version, totally refactored calendar.
