### ISSUE TITLE
Multiple calendars controls on the same page

### ISSUE THREAD

**Issue by Mishu** [Serhioromano/bootstrap-calendar#306]
Hi,

How can I make it to work with 4 calendars on the same page?

Thanks,
Mishu

**Comment by naneutral** [comment]
To fix change css selector in `Calendar.prototype._update_month_year` like this
```javascript
$(self.context.selector+' .cal-month-day, .cal-year-box .span3')
```
instead of
```javascript
$('.cal-month-day, .cal-year-box .span3')
```

**Comment by xzdead** [comment]
I tried this solution but event's don't show after applying changes.

Any ideas?


Many thanks

**Comment by naneutral** [comment]
Youre welcome!

**Comment by angelcabrera** [comment]
Hi, somebody can help me?
i need have 2 instances of calendar in the same page...

that is my code for the first:
`var calendar = $("#calendario-registros").calendar(
				{
					language: 'es-MX',
					tmpl_path: "/recepcion/tmpls-calendar/",
					tmpl_cache: false,
					view: 'month',
					events_source: '/recepcion/calendario-registros.php',
					onAfterViewLoad: function(view) {
						$('.titulo-calendario h3').text(this.getTitle());
						$('.boton button').removeClass('active');
						$('.boton button[data-calendar-view="' + view + '"]').addClass('active');
					},
					classes: {
						months: {
							general: 'label'
						}
					}
				});
			
				$('.boton button[data-calendar-nav]').each(function() {
					var $this = $(this);
					$this.click(function() {
						calendar.navigate($this.data('calendar-nav'));
					});
				});
			
				$('.boton button[data-calendar-view]').each(function() {
					var $this = $(this);
					$this.click(function() {
						calendar.view($this.data('calendar-view'));
					});
				});
			
				$('#first_day').change(function(){
					var value = $(this).val();
					value = value.length ? parseInt(value) : null;
					calendar.setOptions({first_day: value});
					calendar.view();
				});`

and this is for the second one:

`var calendar = $("#calendario-reservas").calendar(
				{
					language: 'es-MX',
					tmpl_path: "/recepcion/tmpls-calendar/",
					tmpl_cache: false,
					view: 'month',
					events_source: '/recepcion/calendario-reservas.php',
					onAfterViewLoad: function(view) {
						$('.titulo-calendario2 h3').text(this.getTitle());
						$('.boton2 button').removeClass('active');
						$('.boton2 button[data-calendar-view="' + view + '"]').addClass('active');
					},
					classes: {
						months: {
							general: 'label'
						}
					}
				});
			
				$('.boton2 button[data-calendar-nav]').each(function() {
					var $this = $(this);
					$this.click(function() {
						calendar.navigate($this.data('calendar-nav'));
					});
				});
			
				$('.boton2 button[data-calendar-view]').each(function() {
					var $this = $(this);
					$this.click(function() {
						calendar.view($this.data('calendar-view'));
					});
				});
			
				$('#first_day').change(function(){
					var value = $(this).val();
					value = value.length ? parseInt(value) : null;
					calendar.setOptions({first_day: value});
					calendar.view();
				});`

but jus one is load correctly, im missing something?.......

**Comment by naneutral** [comment]
Hello set unique calendars variables.
change
var calendar = 
to
var calendar_registros = 
var calendar_reservas = 

AND 
calendar.navigate
to
calendar_registros .navigate
calendar_reservas .navigate

Hope this help you.

**Comment by angelcabrera** [comment]
Thanks a lot, work fine now, clearly this helped.
