### ISSUE TITLE
Disable day view on date click

### ISSUE THREAD

**Issue by TommyZG** [Serhioromano/bootstrap-calendar#325]
Hi,

When you click the number in month view, you get day view. How can I disable this behaviour? I don't want anything to happen if someone clicks the number.

I'm new to JS, of course, so I would appreciate something like "in app.js add option something something" because I don't know what it means to "unbind event" :) Thanks!

**Comment by Matthieusch** [comment]
Simply do this.
```
var calendar = $el.calendar({
    tmpl_path: "/tmpls/",
    views: {
      year:  {
        enable: 1
      },
      month:  {
        enable: 1
      }
      week:  {
        enable: 1
      },
      day:   {
        enable: 0 //disabled
      }
    }
});
```

**Comment by renaudjenny** [comment]
@Matthieusch This solution is perfect for me! Is there a Wiki or something else where all calendar "constructor options" are explained?

**Comment by Matthieusch** [comment]
Hi @renaudjenny, I had to check sources to find it in : https://github.com/Serhioromano/bootstrap-calendar/blob/master/js/calendar.js line 95.

**Comment by renaudjenny** [comment]
@Matthieusch Oh great! It's right that this part explains all *options* by itself. Thanks again :smiley:
