### ISSUE TITLE
How to get date when i click on a day in month view

### ISSUE THREAD

**Issue by DrEtep** [Serhioromano/bootstrap-calendar#332]
Hi, 

I really like this widget, great stuff.
in month view, i click on a day (with or without events). 
I want to populate a label with the date I just clicked on so that i can create a new event for that day. how do i do this ?
Im thinking it goes here, but I cannot find which property to use.

```
                 .on('click', function (event) {
```

> > > > ```
> > > >               $('input.ActiveDate').val(????);
> > > >                        if($('.events-list', this).length == 0) return;
> > > >                        if($(this).children('[data-cal-date]').text() == self.activecell) return;
> > > >                        showEventsList(event, downbox, slider, self);
> > > >                  })
> > > >           ;
> > > > ```

Any help would be much appreciated.

**Comment by surbhig20** [comment]
Could you please give the code for this. I am Trying to perform the same, while clicking o a month view date I want to get the date clicked in the console. But its throwing "undefined"
