### ISSUE TITLE
Original page doesn't work at all

### ISSUE THREAD

**Issue by igrrik** [Serhioromano/bootstrap-calendar#343]
1) Modified webpage doesn't work in chrome 
2) I've downloaded zip again and opened index.html, it doesn't work in chrome or safari
3) I've copied all the code from original source http://bootstrap-calendar.azurewebsites.net, and it doesn't work

Everywhere is one problem: 
Uncaught TypeError: string is not a function  (evaluating'this.options.templates[this.options.view](data)')
calendar:js432

1) This is original index.html from bootstrap-calendar-master archive
![2014-07-09 14 08 27](https://cloud.githubusercontent.com/assets/4175212/3522896/fcc22654-0751-11e4-99ac-e7cde45eab49.png)
![2014-07-09 14 08 59](https://cloud.githubusercontent.com/assets/4175212/3522897/fff359ce-0751-11e4-9734-c5b4a46089dc.png)

2) This is modified index.html, where I've deleted disqus,twitter and other optional elements
Safari:
![2014-07-09 14 06 59](https://cloud.githubusercontent.com/assets/4175212/3522843/97e6c050-0751-11e4-87a0-dbc9d97feafc.png)
Chrome:
![2014-07-09 14 07 31](https://cloud.githubusercontent.com/assets/4175212/3522846/9e8bc4b4-0751-11e4-80cf-02530c58fbc8.png)

3) This is my page I've did everything from quick setup
![2014-07-09 14 09 38](https://cloud.githubusercontent.com/assets/4175212/3522906/150cc264-0752-11e4-8bb9-b5a06ee9cbc3.png)
![2014-07-09 14 10 23](https://cloud.githubusercontent.com/assets/4175212/3522909/1893fae2-0752-11e4-90fa-e596c3254681.png)

**Comment by ashuw20001** [comment]
host all files on server then access link of project  it will run on chrome..
as chrome has security of not accessing file from another origin.
so to avoid the CORS error , keep all those file in server/localhost.
