### ISSUE TITLE
How to refresh source from java script

### ISSUE THREAD

**Issue by hareenmallipeddi** [Serhioromano/bootstrap-calendar#384]
Hi,

I've a ajax service to feed the calendar, how can I refresh current view when clicks on a button (refresh button)?

Regards,
Hareen

**Comment by Joysond** [comment]
calendar.view() does not work

**Comment by eleazan** [comment]
@Joysond it works...

https://github.com/Serhioromano/bootstrap-calendar/blob/master/js/calendar.js#L735

The view funtion calls loadEvents and render.. so, do a "refresh" for all events....

How do you have your source? ;)

**Comment by Joysond** [comment]
@eleazan 
I am loading the events via ajax call,
once I save the events I am doing calendar.view(), It doesn't seem to work

**Comment by eleazan** [comment]
You can check if when you do the calendar.view();, at chrome devs console (for example) you are doing an ajax call to the source? And, if it is loading the new event

**Comment by Joysond** [comment]
I can see the new event if I refresh the page. and I checked the console too the ajax has not been called

**Comment by eleazan** [comment]
How do you set the source var?

**Comment by Joysond** [comment]
I called a function through which the ajax call is made

**Comment by Joysond** [comment]
function getEvents() {
	$.ajax({
    	url: '<%=request.getContextPath()%>/getEvents',
		    dataType: 'json',
		    async: false,
		    success: function(doc) {
		        $(doc).each(function() {
		            eventData.push({
		                id: $(this).attr('systemName'),
		                title: $(this).attr('title'),
		                start: $(this).attr('start'),
		                end: $(this).attr('end'),
	 					description: $(this).attr('description')
		            });
		        });
		    }
		});
}

function displayInCanlendar() {
	calendar = $("#calendar").calendar(
            {
                tmpl_path: "<%=request.getContextPath()%>/css/tmpls/",
                events_source: eventData,
                modal: "#eventDeleteModal",
                modal_type : "template",
                modal_title: function(event) { 
                	document.getElementById("eventDeleteTitle").innerHTML=event.title;
                	systemName = event.id;
                },
            	onAfterEventsLoad: function(events) {
            		if(!events){
            			return;
            		}
            		$.each(events, function(key, val) {
        				$(document.createElement('li'))
        					.html('<p>' + val.title + '</p>');
        			});
            	},
            	onAfterViewLoad: function(view) {
        			$('#calendarHeader').text(this.getTitle());
        			$('.btn-group button').removeClass('active');
        			$('button[data-calendar-view="' + view + '"]').addClass('active');
        		}
            });
	$('.btn-group button[data-calendar-nav]').each(function() {
		var $this = $(this);
		$this.click(function() {
			calendar.navigate($this.data('calendar-nav'));
		});
	});
	
	$('.btn-group button[data-calendar-view]').each(function() {
		var $this = $(this);
		$this.click(function() {
			calendar.view($this.data('calendar-view'));
		});
	});
}
	$(document).ready(function() {
		getEvents();
		displayInCanlendar();
	});

**Comment by eleazan** [comment]
So, you are passing an array( eventData ) and not a function ;) 

Are you calling getEvents(); before calendar.view() ?

**Comment by Joysond** [comment]
yes I am calling it before calendar.view(), still its not displaying newly added events

**Comment by Psmul** [comment]
Hi, sorry for digging into 2015, but I'm also experiencing the same issue. Do You guys found any solution? I'm making async call, after I receive data, I'm trying to refresh/rerender view:

`
$timeout(function() {
                    $scope.calendar._loadEvents();
                    $scope.calendar._render();
                });
`

**Comment by eleazan** [comment]
with $scope.calendar.view() should work.... if your events are getting via AJAX

**Comment by Psmul** [comment]
Unfortunately, it's not working.

`$timeout(function() {
                    
                    $scope.calendar._loadEvents();
                    $scope.calendar._render();


                    $scope.calendar.view();
                });`

It looks like this for now. No progress.

**Comment by eleazan** [comment]
How do you init the calendar?

**Comment by Psmul** [comment]
I'm creating pre-options object, which has:

`
                events_source: function() {
                    return $scope.eventsAndTerms;
                },`

Which (options) are later initialized like this:
`
                        $scope.calendar = angular.element('#calendar').calendar($scope.options);`

**Comment by eleazan** [comment]
No idea for angular but...

Can you do something like:
```
events_source: function() { console.log("exec source"); return $scope.eventsAndTerms; },
```

An check if they output that to the console?

**Comment by Psmul** [comment]
There is output. Okay maybe I didn;t make my statement clear enough. So I have problem with refreshing values, not with first load. On my first load, I get all correct data - no problem here.

Problem is when i hit refresh button in my calendar view, which makes async call for data and next thing it do, is push data to $scope.eventsAndTerms, which responds for data rendered on view. When i push new data to scope.eventsAndTerms (which in most cases is +1 more element than i was before) it does not refresh view with new added object.

**Comment by eleazan** [comment]
Seems that scope.eventsAndTerms is not getting populate inside the function... output that before the return, and check

**Comment by Psmul** [comment]
You are right, it does not get populated with latest values.

**Comment by Psmul** [comment]
I will also mention, that I'm using older version of this lib, which disallows me to update. Is there possible solution without updating? I tried to replace important parts of lib, but it didn't helped at all, so I reverted.

**Comment by eleazan** [comment]
What version? 

I don't remember that render / loadEvents / view functions has major changes...

**Comment by Psmul** [comment]
Not sure what version is it.. But for sure old one, like at least 1,5 year old.

Still I tested it further and there is problem with not receiveing/refreshing latest value. I checked if I'm not breaking reference, but I am not.

**Comment by eleazan** [comment]
O no have idea for angular.. so.. don't know...

But, you can try to avoid one pass... and do the ajax request on the events_source function directly (i use a old version too.. and that is the way i get events and refresh him)

**Comment by Psmul** [comment]
My architecture do not allow to put half of code into this event_source function sadly.

**Comment by eleazan** [comment]
Can you try something like that?

```
$timeout(function() { 
    var replace_events = { events_source : $scope.eventsAndTerms };
    $scope.calendar.setOptions(replace_events); 
    $scope.calendar.view((); 
});
```

Maybe it works...

**Comment by Psmul** [comment]
In part where I call _render?

**Comment by eleazan** [comment]
Yes...

view() call _loadEvents and _render for you...

**Comment by Psmul** [comment]
Hell yea! It helped!

**Comment by eleazan** [comment]
Y're welcome!
