### ISSUE TITLE
Documentation is very insufficient 

### ISSUE THREAD

**Issue by shahidkarimi** [Serhioromano/bootstrap-calendar#389]
The documentation is very insufficient for normal integration. For example I don't find event handling information when a specific event or date is clicked.

**Comment by ToeiRei** [comment]
+1 as there's just going through the source code for now.

**Comment by Ralphiuss** [comment]
+100

**Comment by Calabonga** [comment]
+1 I agree

**Comment by sailens** [comment]
+1

**Comment by cronenborg** [comment]
+1

**Comment by shahidkarimi** [comment]
I recomed using full Calander : http://fullcalendar.io/

On Thu, May 28, 2015 at 2:57 PM, cronenborg <notifications@github.com>
wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Serhioromano/bootstrap-calendar/issues/389#issuecomment-106255133>
> .
>



-- 

Cheers,

*ᔕᕼᗩᕼIᗪ KᗩᖇIᗰI*
http://shahidkarimi.com <http://shahidkiarimi.com>
karimi.shahid@gmail.com
me@shahidkarimi.com
LinkedIn:  http://pk.linkedin.com/in/shahidkarimi
Skype:     shahidkarimi
Cell:        +92 3129 912287

**Comment by cronenborg** [comment]
Please Shahidkarimi, spam us with your calAndErs.

**Comment by shahidkarimi** [comment]
What do you mean @cronenborg?

On Fri, May 29, 2015 at 1:41 PM, cronenborg <notifications@github.com>
wrote:

> Please Shahidkarimi, spam us with your calAndErs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Serhioromano/bootstrap-calendar/issues/389#issuecomment-106746224>
> .
>



-- 

Cheers,

*ᔕᕼᗩᕼIᗪ KᗩᖇIᗰI*
http://shahidkarimi.com <http://shahidkiarimi.com>
karimi.shahid@gmail.com
me@shahidkarimi.com
LinkedIn:  http://pk.linkedin.com/in/shahidkarimi
Skype:     shahidkarimi
Cell:        +92 3129 912287

**Comment by cronenborg** [comment]
Read what you wrote and you'll get the truth, @shahidkarimi.

**Comment by JordanBallew** [comment]
+1

**Comment by truongngoctuan** [comment]
+1111111

**Comment by Serhioromano** [comment]
Why do you place those +1? It is Github folks. Just add one sentence to documentation that you already know about this component. There would be a full documentation already by thtis time.
