### ISSUE TITLE
multiple typos on finnish translation

### ISSUE THREAD

**Issue by Kehet** [Serhioromano/bootstrap-calendar#440]
on finnish translation in `` bootstrap-calendar/js/language/fi-FI.js`` row 65 should be
```
d0: 'sunnuntai',
```
not
```
d0: 'sunnunta',
```

*edit*: also row 32 should be 
```
week:'Viikko {0}',
```
not
```
week:'Week',
```

**Comment by sailens** [comment]
Changed and requested a pull
