### ISSUE TITLE
Events In PHP Script

### ISSUE THREAD

**Issue by rigaspar** [Serhioromano/bootstrap-calendar#446]
Hello Guys,
I am in need of help in setting up the page with script in php and mysql in building the database. Read and re-read the small manual but found very confused and do not know what the structure of have to have for the events are recorded in the MySQL database and how the page code in PHP script. Can you send me or share with me the complete code ??? Thanks

This my code.
````
<!DOCTYPE html>
<html>
<head>
	<title>Twitter Bootstrap jQuery Calendar component</title>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="components/bootstrap3/css/bootstrap.min.css">
    <link rel="stylesheet" href="css/calendar.css">	
</head>
<body>
<div class="container">
<h1>MEU CALENDARIO</h1>

<?php

$start = date('Y-m-d h:i:s', ($_GET['start'] / 1000))."<br/>";
echo "O QUE ISTO DA: ".$start."<br/>";
echo date("Y-m-d H:i:s");

$db    = new PDO('mysql:host=localhost;dbname=bootstrapcalendar;charset=utf8', 'root', 'XXXXXXX');
//$start = $_REQUEST['from'] / 1000;
//$end   = $_REQUEST['to'] / 1000;

$start = "1420890747263";
$end = "1420890747263";

$sql   = sprintf('SELECT * FROM events WHERE `datetime` BETWEEN %s and %s',
    $db->quote(date('Y-m-d', $start)), $db->quote(date('Y-m-d', $end)));

$out = array();
foreach($db->query($sql) as $row) {
    $out[] = array(
        'id' => $row->id,
        'title' => $row->name,
        'url' => Helper::url($row->id),
        'start' => strtotime($row->datetime) . '000',
        'end' => strtotime($row->datetime_end) .'000'
    );
}

echo json_encode(array('success' => 1, 'result' => $out));
exit;
?>
<div class="page-header">
<div id="calendar"></div>
<br/>
    <script type="text/javascript" src="components/jquery/jquery.min.js"></script>
	<script type="text/javascript" src="components/underscore/underscore-min.js"></script>
    <script type="text/javascript" src="components/bootstrap3/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/calendar.js"></script>
    
    <!--<script type="text/javascript">
		
		var calendar = $('#calendar').calendar({
    	events_source: [
        {
            "success": 0,
    "error": "error message here"
        },
    ]});
			
	</script>-->

</div>
</body>
</html>
````
MY DATABASE SQL
Table: events
Rows: datetime, id, name, datetime_end
Record: 2015-01-09 12:38:22, 1, User1, 2015-01-10 12:38:22

Thanks for help me

**Comment by rigaspar** [comment]
<code>
<title>Twitter Bootstrap jQuery Calendar component</title>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="components/bootstrap3/css/bootstrap.min.css">
    <link rel="stylesheet" href="css/calendar.css">	
</head>
<body>
<div class="container">
<h1>MEU CALENDARIO</h1>

<?php

$start = date('Y-m-d h:i:s', ($_GET['start'] / 1000))."<br/>";
echo "O QUE ISTO DA: ".$start."<br/>";
echo date("Y-m-d H:i:s");

$db    = new PDO('mysql:host=localhost;dbname=bootstrapcalendar;charset=utf8', 'root', 'XXXXXXX');
//$start = $_REQUEST['from'] / 1000;
//$end   = $_REQUEST['to'] / 1000;

$start = "1420890747263";
$end = "1420890747263";

$sql   = sprintf('SELECT * FROM events WHERE `datetime` BETWEEN %s and %s',
    $db->quote(date('Y-m-d', $start)), $db->quote(date('Y-m-d', $end)));

$out = array();
foreach($db->query($sql) as $row) {
    $out[] = array(
        'id' => $row->id,
        'title' => $row->name,
        'url' => Helper::url($row->id),
        'start' => strtotime($row->datetime) . '000',
        'end' => strtotime($row->datetime_end) .'000'
    );
}

echo json_encode(array('success' => 1, 'result' => $out));
exit;
?>
<div class="page-header">
<div id="calendar"></div>
<br/>
    <script type="text/javascript" src="components/jquery/jquery.min.js"></script>
	<script type="text/javascript" src="components/underscore/underscore-min.js"></script>
    <script type="text/javascript" src="components/bootstrap3/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/calendar.js"></script>
    
    

</code>

**Comment by eleazan** [comment]
Please, read this [https://guides.github.com/features/mastering-markdown/](Md), and you will know how to paste code here ;)

So, i edited your first comment for a better code display :-)


And now, for your code...

If you set an exit on php, that would.. well, exit, and stop executing. So, all the code (html, js, php... or whatever) that should be executed after exit, never happens.

The php code, should be appart, and thats the event source ;)

**Comment by eleazan** [comment]
Not a calendar issue
