### ISSUE TITLE
Minimum demo errors - what is tmpl_path?

### ISSUE THREAD

**Issue by kalindriv** [Serhioromano/bootstrap-calendar#449]
Hi, I am using node.js and I installed this awesome calendar with bower. 

In order to use it, I started from the demo, slightly modifying it to link all the components. However, I cannot get to see the calendar.

Here is my code:

```html
<!doctype html>
<html>
<head>
	<title>My Calendar</title>
	<link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.min.css">
	<link rel="stylesheet" href="/bower_components/components-font-awesome/css/font-awesome.min.css">
	<link rel="stylesheet" href="/bower_components/bootstrap-calendar/css/calendar.css">
	<style>
		body { padding-top:80px; word-wrap:break-word; }
	</style>
</head>
<body>
<div class="container">
	<div class="jumbotron">
		<h1>My calendar</h1>
		<div id="calendar"></div>
	</div> <!-- /jumbotron -->
</div> <!-- /container -->

<script type="text/javascript" src="/bower_components/jquery/jquery.min.js"></script>
<script type="text/javascript" src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/bower_components/underscore/underscore-min.js"></script>
<script type="text/javascript" src="/bower_components/bootstrap-calendar/js/calendar.js"></script>

<script type="text/javascript">
	var calendar = $("#calendar").calendar(
		{
			tmpl_path: "/tmpls/",
			events_source: function () { return []; }
		});
</script>
</body>
</html>
```

The errors I get on Chrome are:
- GET http://localhost:8080/tmpls/month.html 404 (Not Found)
- Uncaught TypeError: string is not a function

The only thing I see is the h1 title, but nothing after that. I don't really get what the javascript function at the bottom of the file is supposed to do. 

Are there obvious errors in my code? What am I missing?
What is `tmpl_path`? What is it supposed to contain?

Thank you in advance for the help!

**Comment by eleazan** [comment]
The tmpl_path is the template path. These templates are rended with underscore.

I never used bower, but check if exists the tmpls dir: 

https://github.com/Serhioromano/bootstrap-calendar/tree/master/tmpls

With these files ;)

**Comment by kalindriv** [comment]
Thank you *eleazan*, that was exactly the problem! I should have figured it out, but I didn't see the `/tmpl` directory and therefore I could not understand what that variable was for.

For future reference, in the example I posted above, I modified the line
```javascript
tmpl_path: "/tmpls/",
```
with this one
```javascript
tmpl_path: "/bower_components/bootstrap-calendar/tmpls/",
```
I can now see a beautiful calendar! :+1:

**Comment by eleazan** [comment]
Nice!
