### ISSUE TITLE
Events are not showing on Bootstrap calendar?

### ISSUE THREAD

**Issue by Ramesh369** [Serhioromano/bootstrap-calendar#450]
I don't know where the problem lies,
Can you say me the possible reasons for this....!
My problems is events are not displaying on the bootstrap calendar.
I am implemented the whole process from here
https://github.com/Serhioromano/bootstrap-calendar

**Comment by eleazan** [comment]
What's your setup?

**Comment by Ramesh369** [comment]
I am implementing this code using c# and mvc @eleazan

**Comment by eleazan** [comment]
What are your script for feed the events? And your calendar init?

**Comment by Ramesh369** [comment]
i am using the same app.js file .
and my script to feed the event is as follows.
 var options = {
        events_source: [
        {
            "id": 293,
            "title": "Event 1",
            "url": "http://example.com",
            "class": "event-important",
            "start": 1363947600, // Milliseconds
            "end": 1363951200 // Milliseconds
        },
        {
            "id": 293,
            "title": "Event 2",
            "url": "http://example.com",
            "class": "event-important",
            "start": 1364037600, // Milliseconds
            "end": 1364041200 // Milliseconds
        },
        ],
        view: 'month',
        tmpl_path: 'tmpls/',
        tmpl_cache: false,
        day: '2013-03-12',
        onAfterEventsLoad: function (events) {
            if (!events) {
                return;
            }
            var list = $('#eventlist');
            list.html('');

            $.each(events, function (key, val) {
                $(document.createElement('li'))
					.html('<a href="' + val.url + '">' + val.title + '</a>')
					.appendTo(list);
            });
        },
        onAfterViewLoad: function (view) {
            $('.page-header h3').text(this.getTitle());
            $('.btn-group button').removeClass('active');
            $('button[data-calendar-view="' + view + '"]').addClass('active');
        },
        classes: {
            months: {
                general: 'label'
            }
        }
    };

And  I dont know what is meant by ''Calendar init''

**Comment by eleazan** [comment]
Is something like....
```
var calendar = $('#calendar').calendar(options);
```

So.... at first, the start and end looks bad... 

In js you need to set the timestamp with milisecods...

1364037600 is seconds, 1364037600000 miliseconds!

If you add '000' to your times, it should be showed

**Comment by Ramesh369** [comment]
It worked...
Thanq Sooo much...
I have been trying from morning to fix this problem.
With your answer its all done.'
Really, thanks for the help

**Comment by eleazan** [comment]
You're welcome!

**Comment by kdonewdc** [comment]
When changed  day: '2013-03-12', to  '2016-03-12' from app.js, "holidays" listing displaying, but i need to display event listing to current year, How to do that, please help? and how to do display January to April (4 calendars) Calendars to my page?
