### ISSUE TITLE
Question: How to disable "single day" (daily) mode?

### ISSUE THREAD

**Issue by dwk2** [Serhioromano/bootstrap-calendar#454]
Love your calendar. I'm trying to disable the functionality that enables double-clicking on a '.cal-cell' class and single-clicking on a '.data-cal-date' data attribute. We'd like our usage of your calendar to be only in month-view mode, without any ability to jump into "single day" (daily) mode.

I'd be very grateful if you could offer thoughts on how to maintain the focus on the month-view, and interrupt the consequences of the above mentioned clicks. 

The two functions, mentioned above, that trigger the "single day" mode appear to be:
$('*[data-cal-date]').click(function () {....});
$('.cal-cell').dblclick(function () {....});

Thank you!

**Comment by eleazan** [comment]
Yes, that's the click functions... 

I think you can do that after init your calendar:
````
$('*[data-cal-date]').unbind("click");
$('.cal-cell').unbind("dblclick");
````

**Comment by dwk2** [comment]
Thanks eleazan -- that works great!!
For anybody else reading this, I added a function that is called (a) after the calendar init and (b) also on every button click of the "prev" or "next" month buttons. That enables the initial unbind to stay unbound. 

function unbindDailyMode() {
	$('*[data-cal-date]').unbind("click");
	$('.cal-cell').unbind("dblclick");
}
