### ISSUE TITLE
Years not shown correctly when screen is small

### ISSUE THREAD

**Issue by Calabonga** [Serhioromano/bootstrap-calendar#457]
![screen](https://cloud.githubusercontent.com/assets/346209/6074969/7664f382-ae15-11e4-9273-2683600072d9.PNG)

Please can you fix that?

**Comment by eleazan** [comment]
You can add ```col-xs-3``` to every cell on tmpls/year.html (where you has col-md-3). With both classes, should be ok!

**Comment by Calabonga** [comment]
Thanks!!! It's works!
