### ISSUE TITLE
Event Sorting

### ISSUE THREAD

**Issue by wscheper** [Serhioromano/bootstrap-calendar#471]
How is determined which events show up on the top of a day?

I have a requirement in which events of a specific class (in this case event-special) should always be displayed on top of other events. I tried to sort all this events on top in the dataset, but that doesn't seem to work.

**Comment by eleazan** [comment]
It's about time... if event is "all day" (from X hour to X hour!), they should be show on the top

**Comment by wscheper** [comment]
Thank you for your reply. Obviously the event has to be an all day event. But that isn't really the requirement. Regardless of the timeframe of a specific event, it always has to show up on the top. You can also have a "regular" event which is an all day event while showing up on top of the "special" event.

I will dig into the code and see if I can hack something. Consider it closed.

**Comment by eleazan** [comment]
You can do something here:

https://github.com/Serhioromano/bootstrap-calendar/blob/master/js/calendar.js#L481
