### ISSUE TITLE
[bug] Week numbers & 1st day of month

### ISSUE THREAD

**Issue by jarbinier** [Serhioromano/bootstrap-calendar#472]
Hi,

1. Set first day of month=monday, month view
2. Go to a month starting on a sunday (february or march 2015)

Result: 1st week row is "week 10", 2nd week row is "week 10"

![weeknumbers](https://cloud.githubusercontent.com/assets/11628670/6799820/362fefb0-d219-11e4-9b94-09af3c4c1344.png)

**Comment by kadametz** [comment]
Hi,

replace in calendar.js this function.

Date.prototype.getWeek = function() {
	var thursdayDate = new Date(this.getTime() + (3-((this.getDay()+6) % 7)) * 86400000);
	var weekYear = thursdayDate.getFullYear();
	var thursdayWeek = new Date(new Date(weekYear,0,4).getTime() + (3-((new Date(weekYear,0,4).getDay()+6) % 7)) * 86400000); 
	return Math.floor(1.5 + (thursdayDate.getTime() - thursdayWeek.getTime()) / 86400000/7);
};

**Comment by jarbinier** [comment]
Hi Kadametz,

Thanks, your solution works !
