### ISSUE TITLE
Event dot not loading on page load

### ISSUE THREAD

**Issue by pattimcletchie** [Serhioromano/bootstrap-calendar#487]
Does anyone know what might be causing the events to not load when the page auto loads? 

When you click on today all of our events show up but when the full month calendar loads no dots are shown. To see an example please visit our working website, http://www.yellowfolder.com/Workshops-YF.php#calendar-top

I can provide our code if need be but I'm not sure where the error would be to reference within the code.

Thanks for your help.

**Comment by naneutral** [comment]
Because ob first page load you return empty event array
```javascript
        var calendar = $("#calendar").calendar(
            {
                tmpl_path: "/bootstrap-calendar/tmpls/",
                events_source: function () { return []; }
            });         
   ```

**Comment by pattimcletchie** [comment]
Perfect, thank you for your help. That fixed our problem.
