### ISSUE TITLE
Use on CI (Code Igniter)

### ISSUE THREAD

**Issue by adiansyahgit** [Serhioromano/bootstrap-calendar#492]
I have a problem using it on my CI project. the calendar doesn't not appear but the buttons and the event on the right side does.
can u tell me how to fix it?? i done google it but didnt found the answer to solve it

**Comment by adiansyahgit** [comment]
owh, i got it. the "tmpls" should be placed on root. thanx by the way for the calendar

**Comment by Serhioromano** [comment]
> owh, i got it. the "tmpls" should be placed on root. thanx by the way for the calendar

Not necessary on root. You can place them anywhere, just set corresponding parameter `tmpl_path`.
