### ISSUE TITLE
event class 

### ISSUE THREAD

**Issue by atul329** [Serhioromano/bootstrap-calendar#496]
Actually I am creating an event class with variable as defined in events(id, title .. etc). In controller I am parsing the event array object as JSON. The problem is I can't define a variable in event as class and because of that I am not able to color my events dynamically. Although, I am getting a perfect output with all the events having same default color. Please do suggest how can I change the event color dynamically using same method.

**Comment by Serhioromano** [comment]
> The problem is I can't define a variable in event as class and because of that I am not able to color my events dynamically

Why cannot you? Just set different text to `class` property of the event and it will be assigned. Check with inspector. If this class is not described in CSS file, it will not change how things looks.

Important first step is check if it is assigned and then you can investigate why it does not apply color.

Calendar does not know class names. It treats it simply as a string. So it is really does not matter what you place there.
