### ISSUE TITLE
Hours not showing correctly on day view.

### ISSUE THREAD

**Issue by djluis48** [Serhioromano/bootstrap-calendar#506]
Im having an issue where the hours i entered on the event.json file shows at diferent hours on day view. On the event box, it shows a 4 hour of difference and placed accordingly on the grid.

For example: I stated on the event.json that the event will start at 9:00 AM and end on 6:00 PM. On the event box, it says that it will start at 5:00 AM and end on 2:00 PM, and placed accordingly on the grid.

Any idea how to fix this?

**Comment by Serhioromano** [comment]
Could you please show your exact JSON output?

**Comment by djluis48** [comment]
I guess you mean this...

{
	"success": 1,
	"result": [
		{
			"id": "300",
			"title": "Película Red de Parejas",
			"url": "#",
			"class": "event-info",
			"start": "1434740400000",
			"end":   "1434747600000"
			}
	]
}

That event is supposed to start friday june 19 at 7:00 PM and end the same day at 9:00 PM but its showing from 3:00 PM to 5:00 PM.


![peli](https://cloud.githubusercontent.com/assets/12663918/8133644/9190d19a-10f7-11e5-937b-8838cc42ca7c.jpg)

@Serhioromano Btw, thanks for your work here. Its awesome.

**Comment by djluis48** [comment]
Maybe @eleazan can help me out here...

**Comment by eleazan** [comment]
It's more easy if i can view it!

Any url? :P

**Comment by adeiry** [comment]
I have the same issue ! Did you find any solution?

**Comment by eleazan** [comment]
What timezone do you have? 

Whats your event json? And what time has the event on grid?

**Comment by adeiry** [comment]
I fixed the timezone ("Asia/Baku" => Lebanon)
and still messed up ! 

my event json is: 
![image](https://cloud.githubusercontent.com/assets/9880387/9626531/df244b6c-5166-11e5-8464-d3ed9a7c4317.png)

As shown is the example below, I have 2 events: "test" event will start 01/SEP/2015 at 10:40 and ends on 02/SEP/2015 at 00:30 
and the second one "test2" should start on 01/SEP/2015 at 11:29 and ends on 07/SEP/2015 at 11:29 
![image](https://cloud.githubusercontent.com/assets/9880387/9626622/95d43174-5167-11e5-92f8-29b2e1adf132.png)


please can you help me with that issue !!!
