### ISSUE TITLE
Calendar not displaying when Back button is pressed

### ISSUE THREAD

**Issue by pepoteloko** [Serhioromano/bootstrap-calendar#511]
When I click back button on the navigator to go back to the calendar page it does'nt appear.
Looking at the code of the page the div with id 'calendar' has dissapeared.

**Comment by eleazan** [comment]
Seems to be related to your code... 

On the demo webpage doesn't happen :/ (yo can try swtich bootstrap version and return on browser... or visit some example link and return)

**Comment by pepoteloko** [comment]
Oh! it's true!
Thanks for the answer.
