### ISSUE TITLE
bootstrap-calendar and Rails render

### ISSUE THREAD

**Issue by dnguyenchevy** [Serhioromano/bootstrap-calendar#515]
Hey,

I'm trying to embed this calendar component/widget into my Rails application.

I've copied calendar.js and calendar.css over into my application. I cannot get the basic calendar embedded to show up. I was wondering if there's a way to avoid using tmpls within the calendar? I want to strictly go with the month.html tmpls and I was just going to use that to mock up. However, whenever I add tmpls folder to my project (/app/views/tmpls/). The application fails to reach the partials and load the webpage.

Here's my error: [14:14:32.571] TypeError: this.options.templates[this.options.view] is not a function 

Anyone have any input?

**Comment by mrauty** [comment]
Hey,

I believe the templates need to be in a publicly accessible location, I assume you get a 404 when browsing to /app/views/tmpls/month.html?

**Comment by dnguyenchevy** [comment]
Yeah, I am.

**Comment by mrauty** [comment]
Ok, well the templates folder needs to be publicly accessible, or at least that was the fix for me when I got the same error.

**Comment by dnguyenchevy** [comment]
How would you make them publicly accessible? Sorry, I'm just learning rails.

**Comment by mrauty** [comment]
:) I'm not sure myself as I'm not familiar with rails! Do you have an assets folder or anything that you could use? Where are your other public files located such as javascript, css etc..?

**Comment by dnguyenchevy** [comment]
Couldn't get this established. --closed

**Comment by Fibrasek** [comment]
Move the template to the public/ folder
