### ISSUE TITLE
Set URL to event click

### ISSUE THREAD

**Issue by teoSalvetti** [Serhioromano/bootstrap-calendar#516]
I'm using ```jsp``` and Spring STS, and I implemented this calendar into my ```index.jspx```,  I use another url  to get all events with ajax (into another controller).
Now when I click an event I have as url ```/``` but I want to use another url, to go into a correct controller.

I need to set a url on event click.....

How can I do it?? 

Thank you

**Comment by eleazan** [comment]
Well...

When you send the json events, for each event you can set the url.. as you set start and end...
