### ISSUE TITLE
Navigation buttons not working

### ISSUE THREAD

**Issue by dzoeteman** [Serhioromano/bootstrap-calendar#53]
I'm currently having an issue where the navigation buttons aren't doing anything.

This is my code: 

```
<button class="btn" data-calendar-nav="prev"><<</button>
<button class="btn" data-calendar-nav="today">[Today]</button>
<button class="btn" data-calendar-nav="next">>></button>
```

No JS errors appear, nor do I think the prototype.navigate is ever called.

According to the Chrome dev console, JS files are being loaded in the following order:
- jQuery
- jQuery UI
- Bootstrap
- Underscore
- Calendar Language file (nl-NL.js made by me)
- Calendar
- App.js

**Comment by cvcv01** [comment]
I'm having the same problem, but I don't get @gdscei answer above. I've included the app.js into the code, and function names are match

html:

		<button class="btn btn-primary" data-calendar-nav="prev"> Prev</button>
		<button class="btn btn-default" data-calendar-nav="today">Today</button>
		<button class="btn btn-primary" data-calendar-nav="next">Next </button>

		<button class="btn btn-warning" data-calendar-view="year">Year</button>
		<button class="btn btn-warning active" data-calendar-view="month">Month</button>
		<button class="btn btn-warning" data-calendar-view="week">Week</button>
		<button class="btn btn-warning" data-calendar-view="day">Day</button>


app.js

	$('.btn-group button[data-calendar-nav]').each(function() {
		var $this = $(this);
		$this.click(function() {
			calendar.navigate($this.data('calendar-nav'));
		});
	});

	$('.btn-group button[data-calendar-view]').each(function() {
		var $this = $(this);
		$this.click(function() {
			calendar.view($this.data('calendar-view'));
		});
	});

So not sure why it's not doing anything when I click any of those buttons

Any ideas? Thanks

**Comment by eleazan** [comment]
Try with 
```
$('button[data-calendar-nav]') ....
$('button[data-calendar-view]') ....
````

**Comment by cvcv01** [comment]
Thanks @eleazan , but it didn't work. I'm guessing it has to do with the reference to the bootstrap-calendar javascript files in my framework. I'll post the solution here when I find the answer. Thanks

**Comment by cvcv01** [comment]
Didn't find the solution. I'm trying to figure out why it doesn't go through the jquery.each() function

My HTML looks like this:

	<div class="container">
		<div class="pull-right form-inline">
			<div class="btn-group">
				<button class="btn btn-primary" data-calendar-nav="prev"><< Prev</button>
				<button class="btn" data-calendar-nav="today">Today</button>
				<button class="btn btn-primary" data-calendar-nav="next">Next >></button>
			</div>
			<div class="btn-group">
				<button class="btn btn-warning" data-calendar-view="year">Year</button>
				<button class="btn btn-warning active" data-calendar-view="month">Month</button>
				<button class="btn btn-warning" data-calendar-view="week">Week</button>
				<button class="btn btn-warning" data-calendar-view="day">Day</button>
			</div>
		</div>
	</div>	
		

I use jquery :

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
	
In app.js, I used the debugger and it goes to the first line of the functions below, but it doesn't go IN the functions:

	$('.btn-group button[data-calendar-nav]').each(function() {
		var $this = $(this);
		$this.click(function() {
			calendar.navigate($this.data('calendar-nav'));
		});
	});

	$('.btn-group button[data-calendar-view]').each(function() {
		var $this = $(this);
		$this.click(function() {
			calendar.view($this.data('calendar-view'));
		});
	});	
	
Is it the syntax in  --> $('.btn-group button[data-calendar-view]').each(function()  <-- ?

I tried jQuery v1.10.2 like it is used in http://bootstrap-calendar.azurewebsites.net/, but no luck.

Any ideas?

Thanks

**Comment by cvcv01** [comment]
Issue not resolved, here is a live example of what I mean.

http://www.vilela.co/test/

**Comment by eleazan** [comment]
Add the 
````
$('.btn-group button[data-calendar-nav]').each(function() {
		var $this = $(this);
		$this.click(function() {
			calendar.navigate($this.data('calendar-nav'));
		});
	});

	$('.btn-group button[data-calendar-view]').each(function() {
		var $this = $(this);
		$this.click(function() {
			calendar.view($this.data('calendar-view'));
		});
	});
``` to your main html after the calendar loads 

Should be something like 
````
var calendar = $('#calendar').calendar({
		events_source: [
			{
				"id": 293,
				"title": "Event 1",
				"url": "http://example.com",
				"class": "event-important",
				"start": 1437507900000, // Milliseconds 
				"end":   1437508639654 // Milliseconds
			}
		],
		tmpl_path: "tmpls/"

		});
$('.btn-group button[data-calendar-nav]').each(function() {
		var $this = $(this);
		$this.click(function() {
			calendar.navigate($this.data('calendar-nav'));
		});
	});

	$('.btn-group button[data-calendar-view]').each(function() {
		var $this = $(this);
		$this.click(function() {
			calendar.view($this.data('calendar-view'));
		});
	});
````

**Comment by cvcv01** [comment]
@eleazan you're a genius. Thank you so much.

Problem was that app.js (contains the jQuery each() functions) was declared in the head, but it needs to be declared after the HTML and script for it to work properly.

Wrong order:

- app.js (declared in head)
- HTML (buttons)
- script

Good order:

- HTML (buttons)
- script
- app.js (declared in body)

**Comment by kagexander** [comment]
I am also facing similar issue. My navigation buttons are not working .The calendar is getting rendered in month mode always. 

Appreciate any suggestions.
