### ISSUE TITLE
How I can use bootstrap-calendar in ASP.NET WebForms

### ISSUE THREAD

**Issue by vicebetancourt** [Serhioromano/bootstrap-calendar#533]
I have write the code snippet below

var calendar = $("#calendar").calendar({
            events_source: [
                {
                    "id": 293,
                    "title": "Event1",
                    "url": "http://example.com",
                    "class": "event-important",
                    "start": 12039485678000, // Milliseconds
                    "end": 1234576967000 // Milliseconds
                }
            ],
            view: 'month',
            tmpl_path: '../../Content/plugins/bootstrap-calendar/tmpls/',
            tmpl_cache: false,
            day: '2013-03-12',
        })

but I get an error
![captura de pantalla 2015-08-02 19 20 38](https://cloud.githubusercontent.com/assets/10731648/9028828/9a773160-394b-11e5-9a9f-7c37c546f5f6.png)

**Comment by eleazan** [comment]
You need include underscore.js
