### ISSUE TITLE
Set href tag on Time Display in Day View

### ISSUE THREAD

**Issue by AndrewPaget** [Serhioromano/bootstrap-calendar#535]
In day view the time column shows likes this:

<div class="span1 col-xs-1"><%= cal._hour(i, l) %></div>

I would like to use a data attribute like this:

'<div class="span1 col-xs-1"><a href="javascript:void(0);" class="do-booking" data-datetime="2015-08-10 11:00"><%= cal._hour(i, l) %></a></div>'

Is it possible to get that date format in to the data-datetime attribute. If so, how? I have tried various methods. I know that <%= cal._hour(i, l) %> makes the hour and minute but what about the date.

My aim is that when a user clicks the time a:link in the day view, both the current date (in the view) AND time is passed to a form, where the $_POST['datetime'] is populated with the GET value passed by the href click.

Example: data-datetime="2015-08-10 18:20"

Can this be done?

**Comment by eleazan** [comment]
Well, on day view... 

When you have "event" var, you can get the event.start and event.end (they are in ms format!). So, you can convert it, and shows a date... or pass them and work with that on backend!

For example, on [day](https://github.com/Serhioromano/bootstrap-calendar/blob/master/tmpls/day.html#L52) you can change it for:
````
<a href="<%= event.url ? event.url : 'javascript:void(0)' %>" data-event-id="<%= event.id %>"
				   data-event-class="<%= event['class'] %>" class="event-item" data-event-start="<%= event.start %>" data-event-end="<%= event.end %>">
					<%= event.title %></a>
````

**Comment by AndrewPaget** [comment]
![template-snapshot](https://cloud.githubusercontent.com/assets/8135582/9193435/486ed104-400b-11e5-8930-88eb6bc3b8fb.jpg)

To make it a little easier to understand, I have included a snapshot image. Please see attached.

As you can see, I have place the current day view Date into data-datetime tag for 11.00 am.

I am trying to achieve a date format in the data-datetime like this. data-datetime="2015-08-11 11:00"

So, when the user clicks the "time" link (in the left column of day view calendar) it will pass the data-datetime value to a form.

I just need to be able to format the date in that tag like 0000-00-00 00:00

Thanks for your assistance.

**Comment by AndrewPaget** [comment]
OK. I got this resolved with:

var d = new Date(this.getTitle());
var date = d.toISOString().slice(0,10);

Used jquery to set the text of the data-date="date" // Sets the data-date to var date
Used data-time="<%= cal._hour(i, l) %>" //Holds the calendar time

var datetime = $(this).data('date') + ' ' + $(this).data('time')
$.get('form.php?datetime='+datetime, function(data) {etc etc etc}

Now datetime field in form is populated with $_GET['datetime'] value

Voila!
