### ISSUE TITLE
can't find templates and this.options.templates not a function errors...cannot fix. 

### ISSUE THREAD

**Issue by thebkbuffalo** [Serhioromano/bootstrap-calendar#538]
Hey, I'm having 2 serious issues that are completely stopping me from getting this calendar up and running.  

First:
I get this error ```Uncaught TypeError: this.options.templates[this.options.view] is not a function``` which I can't seem to find a fix for, and not even sure how to fix this one.

the second error seems like it shouldn't be that big of an issue...yet it really is.  
```GET http://localhost:3000/tmpls/month.html 404 (Not Found)```

No matter what I do or where I move these files to be accessible, they can never seem to be found.  Everything needed is loaded in and accessible (jquery, bootstrap, underscore, moment).  Any and all help will be greatly appreciated!  Thank you!!!

Javascript:
```
$(document).ready ->
  calendar = $('#calendar').calendar(
    tmpl_path: '/tmpls/'
    events_source: ->
      [
        {
          "id": 293,
          "title": "Event 1",
          "url": "http://example.com",
          "class": "event-important",
          "start": 12039485678000,
          "end": 1234576967000
        }
      ]
    )
```

HTML:
```
- content_for :head do
  = render('layouts/admin/head')
  
h1 calendar
#calendar
```

**Comment by eleazan** [comment]
Both errors are the same...

The error is that ````tmpls/month.html````, and the other templates, seems to be unaccesible. 

So, first, check that if you go to ````http://localhost:3000/tmpls/month.html```` you see the month template.

If not, you need to set accesible, or knows the path for access month! Then, you can configure the path var and fix that error!

**Comment by thebkbuffalo** [comment]
@eleazan I figured that.  I've since done a whole bunch with configuring bower for Rails and setting up the asset pipeline, and have all my bower files in my vendor files, but have no idea how to get those tmpls renderable.  Any idea on how to make them public/findable in a rails app?  Thank you!

**Comment by eleazan** [comment]
i never use rails...

you are using RoR? According to http://www.tutorialspoint.com/ruby-on-rails/rails-directory-structure.htm should be on public/...

**Comment by thebkbuffalo** [comment]
@eleazan Thank you so much!!  I'm dumb and probably should've dropped those tmpls in my public folder from the get-go.  Thank you again.

**Comment by eleazan** [comment]
You are welcome!

**Comment by bajabob** [comment]
@thebkbuffalo So i was in this exact same situation. Fixed it as mentioned above. However, I cannot get any data to load into the calendar. Everything else seems to be working. I can moved through all the pages, etc.
