### ISSUE TITLE
Event by click

### ISSUE THREAD

**Issue by Eylwyht** [Serhioromano/bootstrap-calendar#544]
Hi everyone,

(Sorry for my bad english) I wanted first to thank you for this awesome calendar !

I saw that we have to feed manually the calendar (by function, array or url) but is it possible to create an event just by clicking on a (random) date and save it on a bdd ? I've tried a lot of time, but i think that i don't have enough skill in php to make it. Can someone help me or give a tip ?

In expectation of a positive response,

Kind regards.

**Comment by eleazan** [comment]
Yeah, you can...

i have something like that (it's an option of calendar! )
````
onAfterViewLoad: function(view) {
				if(view == "month") {
				 	$("#calendar .cal-month-day").click(function(e) {
						var clicked_date = $(this).find('span').attr('data-cal-date');
						//Do whatever you want. probably, a $.post or something to add the record on your db
							
						}
					});
				}
			},
````

You can see how i implement that (i have more things on the function!). That's an example for month view ;)

**Comment by Eylwyht** [comment]
Thank you so much, i'll try to make it work ;)

And thank you eleazan to be very active on the issue :)

**Comment by eleazan** [comment]
I think all works, closing issue! ;)

**Comment by Rafael768** [comment]
Text translated in google. Good days, I could have realized it thus, in a new file .js attached to the page since on having changed sight JQuery it was not coming to the object.

$(document).on("click","#calendar .cal-month-day span",function() {
                        var clicked_date = $(this).attr('data-cal-date');
                        alert(clicked_date);
                        return false;
                    });
From here, this is super competitivly to do thousands of things, thank you very much for the contribution.
