### ISSUE TITLE
How to set Time Format 12 hours without checking the checkbox?

### ISSUE THREAD

**Issue by glenbacs** [Serhioromano/bootstrap-calendar#556]
I am trying to make my calendar 12 hours without the user checking on checkbox, I tried to edit js but i find it very difficult and not functioning. help?

**Comment by eleazan** [comment]
When you init the calendar, add the option format12: true

Ps: sorry, i'm from mobile, later i add an example

**Comment by eleazan** [comment]
````
var calendar = $("#calendar").calendar(
            {
                tmpl_path: "/tmpls/",
                format12: true,
                events_source: function () { return []; }
            });         
````
