### ISSUE TITLE
Usage URL with GET parameters?

### ISSUE THREAD

**Issue by roman-panshin** [Serhioromano/bootstrap-calendar#563]
How can I use URL with GET parameters to activate day or week. 
I trying to use 
> http:/somesite.ww/someurl.html?data-cal-date=2015-06-01&data-cal-view=month

but havnt result...

**Comment by Serhioromano** [comment]
You want that opened page automatically highlighted particular date and view?

So on the page where you initialize calendar you have to get those parameter first. Please [read this](http://stackoverflow.com/questions/979975/how-to-get-the-value-from-the-url-parameter) how you might do that.

Now using those parameters initialize calendar accordingly.

**Comment by roman-panshin** [comment]
Thanx! 
(if someones gona need it) 
I've set this 
````
var dayone = 'now';
var monthone = 'month';

function getURLParameter(name) {
  return decodeURIComponent((new RegExp('[?|&]' + name + '=' + '([^&;]+?)(&|#|;|$)').exec(location.search)||[,""])[1].replace(/\+/g, '%20'))||null
}

var dayone1 = getURLParameter('dayone');

if(!dayone1) {
dayone = 'now';
}
else{
dayone = dayone1;
}

var monthone1 = getURLParameter('monthone');

if(!monthone1) {
monthone = 'month';
}
else{
monthone = monthone1;
}
````
    
in the begining of app.js
and change
````
	var options = {
		...
		view: monthone,
		...
		day: dayone,
		...
	}
````

Now it works!    
`URL?dayone=2015-09-01&monthone=day` 
e t.c.

**Comment by Serhioromano** [comment]
Perfect! Nice job :+1:
