### ISSUE TITLE
Tooltip is not a function

### ISSUE THREAD

**Issue by DazzlingDevelopment** [Serhioromano/bootstrap-calendar#566]
I love this calendar, and I've slowly been piecing it together (the lack of documentation does make that rather hard). However, I have run into an error. When I run the webpage, this error pops up:
`$('*[data-toggle="tooltip"]').tooltip is not a function. (In '$('*[data-toggle="tooltip"]').tooltip({container: 'body'})', '$('*[data-toggle="tooltip"]').tooltip' is undefined`

The error originates in the calendar.js file, and is located at this line:
```javascript
$('*[data-toggle="tooltip"]').tooltip({container: 'body'}); // Line 938
```

I'm not sure what is causing this error, and how to fix it. Any ideas?

**Comment by DazzlingDevelopment** [comment]
Got it! For those wondering, it appears I was using a different version of the `bootstrap.js` than I needed to be using. The version I was using uses the `attr()` function to provide tooltips - not the `tooltip()` function. Since I wanted to continue using the current version of bootstrap, I changed the code in `calendar.js` to:
```javascript
$('*[data-toggle="tooltip"]').attr({container: 'body'}); // Line 938
```

**Comment by p0six** [comment]
@DazzlingDevelopment you're a king among men!! Thanks for posting this fix :)
