### ISSUE TITLE
Is it possible to change how days are displayed?

### ISSUE THREAD

**Issue by plok27** [Serhioromano/bootstrap-calendar#571]
Hello!

Does anyone know what do I have to do to see all days of the month in a row? Something like the week-view option, but with all the days of the month in it. I would also like to add different rows. I need to check if some employees do something (morning/afternoon):

![image](https://cloud.githubusercontent.com/assets/15833379/11146704/d00dbc52-8a10-11e5-8391-e82a0de9ece3.png)

I'm quite new to css and js and I'm having some real problems to create another view.

Thanks a lot !!

**Comment by eleazan** [comment]
You need to create a custom view for month... and maybe a little coding in calendar :(
