### ISSUE TITLE
Some Events Show on Multiple Days??

### ISSUE THREAD

**Issue by idevwebs** [Serhioromano/bootstrap-calendar#577]
For some reason, I get events showing up on multiple days. I give an event start and end time like this: strtotime(2015-12-02 06:30:00).000 and strtotime(2015-12-02 018:30:00).000 which is the same day, but the event will display on both the 2nd and the 3rd. I'm not sure why. It's bugging me since I've put in a lot of time integrating this calendar (which is very cool) but this bug needs fixing... or if user error, how to fix? 

![capture1](https://cloud.githubusercontent.com/assets/9595421/11676597/1b9698b2-9df1-11e5-8458-fdd71668495c.PNG)
![capture2](https://cloud.githubusercontent.com/assets/9595421/11676598/1bb0b2f6-9df1-11e5-898b-04f4e43a8d36.PNG)

Please let me know as soon as possible. Thank you

**Comment by idevwebs** [comment]
Update:
So this was not an issue with the calendar itself. It was an issue with php strtotime which was providing incorrect values (don't know why)...

So if you're doing as the docs for this script say, like so:

$start = strtotime($db['eventdate'].' '.$db['eventtime']) . '000';

And are having issues... then try using mysql's unix_timestamp, like so:

mysql query:
  select
  unix_timestamp(concat(eventdate,' ',eventstarttime))*1000 as started, 
  unix_timestamp(concat(eventdate,' ',eventendtime))*1000 as ended,

That fixed it for me :)

**Comment by eleazan** [comment]
Nice!
