### ISSUE TITLE
can not hide weekbox

### ISSUE THREAD

**Issue by JosephP91** [Serhioromano/bootstrap-calendar#580]
Hi,
I'm trying to hide the weekbox with the following code, but it does not work:

calendar.setOptions({weekbox: false});
calendar.view();

How can I do? Thanks!

**Comment by NLKNguyen** [comment]
Upvote!

These settings don't hide the weekbox as described in #470
```
...
display_week_numbers: false,
weekbox: false,
...
```

**Comment by KhanMaytok** [comment]
The calendar.min.js is now updated and the options are working, please consider close the issue :D
