### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by hypery2k** [Serhioromano/bootstrap-calendar#585]
any plans for a new version? The last tagged release (0.2.4) is really old not working. There are a lot changeds currently pushed on master without any new release :(

**Comment by darkleaf** [comment]
:+1:

**Comment by johan-v-r** [comment]
bump

**Comment by eleazan** [comment]
+1!

@Serhioromano doesn't have time now... but, i want too a new version! Maybe an async complete version

**Comment by Serhioromano** [comment]
I have just released new version 0.2.5.
