### ISSUE TITLE
How to set default language - for dummie

### ISSUE THREAD

**Issue by zielonezabki** [Serhioromano/bootstrap-calendar#594]
Can someone just paste the formula and tell me in which file i have to place it? That's the only problem i have with this wonderful calendar.

**Comment by naneutral** [comment]
Here is an example
`$("#yourid").calendar(
                {
                    view : "month",
                    language : 'ru-RU',
                    ...
                }`

"language" folder with locale js-file shoud place near with calendar.js

**Comment by arvidw** [comment]
Sorry i can't quite understand how to do this.

"$("#yourid").calendar( { view : "month", language : 'ru-RU', ... }" - what does this do? is it complete? where, and in which file should i put it?

Thanks!

**Comment by naneutral** [comment]
in a folder with calendar.js you must have another folder named "language". That folder must contains localization js file.
Example:
/js
--/language
----ru-RU.js
----fr-FR.js
--calendar.js

Then in config of your calendar you set language : 'ru-RU' or language : 'fr-FR', depends of your language files.

**Comment by arvidw** [comment]
Oh, ok. But where do i "config" my calendar? Serhioromano wrote something similar: "When you initializing the calendar, you have to specify this language code.." Can't seem to figure out where i should insert the code..

I do realise i sound like a noob.. But i do really appreciate your help. So thanks a lot.

**Comment by naneutral** [comment]
This is "the config" 
`{ view : "month", language : 'ru-RU', ... }`

You place code like that in html file and got your calendar on page
```
<div id="yourid"></div>
<script type="text/javascript">
$("#yourid").calendar( {
    view : "month", 
    language : 'ru-RU'
});
</script>
```

**Comment by arvidw** [comment]
"yourid" - what is this? where do i find my id?

**Comment by eleazan** [comment]
You should be has a "initialitzation" of your calendar, something like that: 

```
var options = {

		events_source: 'events.json.php',
		view: 'month',
		tmpl_path: 'tmpls/',
		tmpl_cache: false,
		...
	};

	var calendar = $('#calendar').calendar(options);
```
(that's extracted from app.js!)

So, for set your language, you need to add language to the options array, something like that:
```
var options = {
		language : 'ru-RU',
		events_source: 'events.json.php',
		view: 'month',
		tmpl_path: 'tmpls/',
		tmpl_cache: false,
		...
	};

	var calendar = $('#calendar').calendar(options);
```

So, that's the way!

PD: Obviusly, before you need to add the language script to your index!
PD2: Where i wrote ..., it can be other options!
PD3: Sorry for my english

**Comment by arvidw** [comment]
Eleezan! Fucking master! Thanks!

Really, thanks a lot!

**Comment by eleazan** [comment]
You're welcome!

But, it's something basic!
