### ISSUE TITLE
Search Functionality For Custom data and Year 

### ISSUE THREAD

**Issue by Madhu1207** [Serhioromano/bootstrap-calendar#603]
How to implement search functionality in calendar. 
Ex: I have events in category wise and stored in database  from that i want to show particular category
when category selected from select dropdown. 
I have tried in so many ways but i didn't get any solution 
Please help me out

**Comment by eleazan** [comment]
You can do that

```javascript
events_source: function(start, end, timezone) {
				
				var events = [];
				var ret = [];
				$.ajax({
					url:      'agenda.json.php?from='+start.getTime()+'&to='+end.getTime()+'&search='+$("#search").val(),
					dataType: 'json',
					type:     'GET',
					async:    false
				}).done(function(json) {
						if(!json.success) {
							$.error(json.error);
						}
						if(json.result) {
							ret['events'] = json.result;
							ret['weeks'] = json.weeks;
						}
					});
					
				return ret;
			},
```
And then, you only need to call `calendar.view()` on change, keypress, or whatever you want on #search!

**Comment by joe11joe** [comment]
I had tried to implement this (Search) in my codeigniter project. But the events are not getting displayed. Can anyone help me in this regard.

**Comment by joe11joe** [comment]
**Following is the javascript code from my view file:**
<script type="text/javascript">
	$('#search').on('change', function() {
	  calendar.view()
	});
	var calendar = $("#calendar").calendar(
		{
			events_source: function(start, end, timezone) {
			var events = [];
			var ret = [];
			$.ajax({
					url:      '<?php echo base_url();?>calendar/get_calendar/'+$("#search").val(),
					dataType: 'json',
					type:     'GET',
					async:    false
				}).done(function(json) {
						if(!json.success) {
							$.error(json.error);
						}
						if(json.result) {
							ret['events'] = json.result;
							ret['weeks'] = json.weeks;
						}
					});
				return ret;
			},
			tmpl_path: "<?php echo base_url();?>assets/bootsrap-calendar/tmpls/",
			language: 'en-US',
			first_day: 1,
			format12: 1,
			weekbox: 1,
			onAfterEventsLoad: function(events) {
				if(!events) {
					return;
				}
				var list = $('#eventlist');
				list.html('');
				$.each(events, function(key, val) {
					$(document.createElement('li'))
						.html('<a href="' + val.url + '">' + val.title + '</a>')
						.appendTo(list);
				});
			},
			onAfterViewLoad: function(view) {
				$('.page-header h3').text(this.getTitle());
				$('.btn-group button').removeClass('active');
				$('button[data-calendar-view="' + view + '"]').addClass('active');
				if (view == 'day') { verifyConflictEvents();}
			},
		});	
</script>


**Controller Function:**

public function get_calendar($search='') {
	$events = $this->calendar_model->get_sample_calendar($search);
	echo json_encode($events);
}

**In the model I use if condition like the following to get the result** 
if($search){
	$this->db->where('search_id', $search);
}


When I run the event source url in the browser in a new tab, I am able to get the desired result in json form.
But the events are not getting loaded in the calendar view.

**Comment by eleazan** [comment]
avoid this: ```ret['weeks'] = json.weeks;``` its a bit custom for me, sorry :( 

And that probably is getting you an error beacuse json.weeks not exists

**Comment by joe11joe** [comment]
I have removed json.weeks and I still don't get the events in the calendar. You can see the encoded **json data** that I receive bleow (which is formatted as you instructed):

{
    "success": 1,
    "result": [
        {
            "id": "11",
            "title": "LITTLE HOUSE, CRAFTIER ROAD, BIG CITY, POSTAL COUNTY",
            "start": "1464687000000",
            "end": "1464688800000.000000",
            "color": "#999999",
            "start_date": "31-05-2016",
            "booking_time": "03:00 PM",
            "agent_name": "Nithish Kumar",
            "property_address": "LITTLE HOUSE, CRAFTIER ROAD, BIG CITY, POSTAL COUNTY",
            "clerk_name": "Infant Kishore",
            "url": "http://localhost:801/svnprojects/SMI/Source/manage/bookings/update/11"
        },
        {
            "id": "12",
            "title": "CUTE HOUSE, CRAFTIER ROAD, BIG CITY, POSTAL COUNTY",
            "start": "1464687000000",
            "end": "1464688800000.000000",
            "color": "#999999",
            "start_date": "31-05-2016",
            "booking_time": "03:00 PM",
            "agent_name": "Nithish Kumar",
            "property_address": "CUTE HOUSE, CRAFTIER ROAD, BIG CITY, POSTAL COUNTY",
            "clerk_name": "Infant Kishore",
            "url": "http://localhost:801/svnprojects/SMI/Source/manage/bookings/update/12"
        }    
    ]
}


If possible can you give me any url which has the sample working copy of this search!

**Comment by eleazan** [comment]
It's a backend url :( 

Try
````javascript
events_source: function(start, end, timezone) {
        var events = [];
        $.ajax({
                url:      '<?php echo base_url();?>calendar/get_calendar/'+$("#search").val(),
                dataType: 'json',
                type:     'GET',
                async:    false
            }).done(function(json) {
                    if(!json.success) {
                        $.error(json.error);
                    }
                    if(json.result) {
                        events = json.result
                    }
                });
            return events;
        },

````

If works, i will edit the first response to avoid confusions... my project was two years ago, and i modified some things... xD

**Comment by joe11joe** [comment]
Thanks a lot @eleazan!

It works well. I could perform the search now. Thank you so much.
