### ISSUE TITLE
bootstrap calendar how to disable auto dst conversion?

### ISSUE THREAD

**Issue by madzohan** [Serhioromano/bootstrap-calendar#608]
I've faced with a problem:
- sending request to backend for a datetime - then I simply want to display it in UTC (same as from backend) ... but seems plugin performs DST conversion ...

How I can disable this behavior and simply display event as it is, without DST conversion?

**Comment by Serhioromano** [comment]
I think conversion is done by local JS. May be you can add Time Zone offset and adjust it what you need?
