### ISSUE TITLE
day view click on timeslot does not work

### ISSUE THREAD

**Issue by interman** [Serhioromano/bootstrap-calendar#618]
Is anyway to add click() on the time slot at day view? I try to add $('.cal-day-hour-part').click() but never been called if I click the time slot. Look like $('#cal-day-panel) will capture all mouse event and never propagate to underneath div element.

**Comment by daveseco7** [comment]
This is something that i'd also like to use, but have not yet figure it out :/

**Comment by daveseco7** [comment]
if i understoud correctly you want a click listener on a day view row rigth?

Try this : 
`		onAfterViewLoad: function(view) {

			$('#cal-day-box #cal-day-panel #cal-day-panel-hour .cal-day-hour .row-fluid.cal-day-hour-part').unbind('click');
			$('#cal-day-box #cal-day-panel #cal-day-panel-hour .cal-day-hour .row-fluid.cal-day-hour-part').click( function() {
				//When click on hour in the day view
				console.log($(this));

				var date= $(this).data('calendar-day');
				var time = $(this).children('.span1').children('b').html();
				alert(date);
				alert(time);
			});
`

**Comment by interman** [comment]
I try the code segment, it doesn't work!   :(

Is it possible to implement a callback, like onDayTimeClick(daytime),  in calendar object?   It will  fire when user click on day/time slot in any views (year, month, week, day).

**Comment by interman** [comment]
I did the experience - 

1) only this will work but cannot get day and time on click.

        onAfterViewLoad: function(view) {

            $('#cal-day-panel').click( function() {
                //When click on hour in the day view
                console.log($(this));

                var date= $(this).data('calendar-day');
                var time = $(this).children('.span1').children('b').html();
                alert(date);
                alert(time);
            });

2) when I inspect any time slots (<div id="cal-day-panel-hour>) element in day view.   Browser DOM inspector always show <div id="cal-day-panel"....>, not show the <div id="cal-day-panel-hour">.  look like it is a bug that invisible cal-day-panel element is above all cal-day-panel-hour elements and mouse click is captured by cal-day-panel and it is not propagate the click event to underneath cal-day-panel-hour elements.

I try both IE and Chrome got same behaviour.

**Comment by daveseco7** [comment]
With the code i've shown to you, i also cannot get the day date, but manage to instantiate a new momentjs object passing the H3 header that contains the selected day. (not a good solution, but it works until i find a better one).
The event on click listener should work the way i presented, i have found that little code block in a different thread written by the project developer himself.

**Comment by eleazan** [comment]
Well... i think that code is mine xD

So, i modified the day template, to add the calendar-day info, with something like that:
```html
<div class="cal-day-hour">
					<% for(l = 0; l < in_hour; l++){ %>
						<div class="row-fluid cal-day-hour-part" data-calendar-day="<%= cal.options.day %>">
							<div class="span1 col-xs-1"><b><%= cal._hour(i, l) %></b></div>
							<div class="span11 col-xs-11"></div>
						</div>
				<% }; %>
				</div>
```

But, i no remember if i modified some JS... you can try with that ;)

**Comment by interman** [comment]
The following code still is copied from my project.   I still cannot catch the click event.
Is it anything I miss in my code?

```
var calendar = $("#calendar").Calendar(
{
    tmpl_path: "/tmpls/",
    modal: "#events-modal",
    modal_type: "buttonDiv",
    events_source: "/Calendar/GetAllEvents",
    tmpl_cache: false,
    onAfterViewLoad: function (view) {
            debugger;
            $('#cal-day-box #cal-day-panel #cal-day-panel-hour .cal-day-hour .row-fluid.cal-day-hour-part').unbind('click');
            $('#cal-day-box #cal-day-panel #cal-day-panel-hour .cal-day-hour .row-fluid.cal-day-hour-part').click(function () {
                //When click on hour in the day view
                console.log($(this));

                var date = $(this).data('calendar-day');
                var time = $(this).children('.span1').children('b').html();
                alert(date);
                alert(time);
            });
    },
});

```

**Comment by eleazan** [comment]
I think that os the same that i have... 

So, have you modified the templates? Have you some public url? I cannot replicate your bug :(

**Comment by eleazan** [comment]
Tested. You can do that with that code, and the modded tmpls.

**Comment by andytwoods** [comment]
Without editing templates, you can do this:
```
var calendar = $("#calendar").calendar(
    {
      tmpl_path: "{% get_static_prefix %}calendar/tmpls/",
      events_source: '{% url 'calendar_json' study.id  %}',
      first_day: '1',
      onAfterViewLoad: function (view) {
        $('.cal-day-hour-part').click(function () {
          console.log($(this).children().first().text())
        })
      }
    });

```
