### ISSUE TITLE
day view event link

### ISSUE THREAD

**Issue by mmguide2003** [Serhioromano/bootstrap-calendar#619]
Where do I edit the day view so I can create a link for the the event. Currently it has link in the dropdown but not in the full day view.

**Comment by eleazan** [comment]
@mmguide2003 you can edit that on tmpls/day.html... but, it should be linked... >_<

**Comment by mmguide2003** [comment]
Yes that's what I tried but strangely it doesn't make any difference to the page.

**Comment by eleazan** [comment]
It's a public url?

**Comment by mmguide2003** [comment]
Here is a test example:
http://one2teach.com/calendar

**Comment by eleazan** [comment]
Ok...

Your [tmpls/day.html](http://one2teach.com/bootstrap-calendar-master/tmpls/day.html) is different that bootstrap master tmpls day...

**Comment by mmguide2003** [comment]
Just forgot to upload the convert but not the issue. I changed the day.html to the one on here (Github) but still no luck.No changes in day.html register.

**Comment by eleazan** [comment]
Of course, sorry...

The correct path is the tmpls/ dir in the root... not at bootstrap-calendar-master/tmpls... 

So, you need to init with `tmpl_path` changed...

**Comment by mmguide2003** [comment]
Yes I had that before but thought would try from site root. Have changed that. so now 
tmpl_path:    'tmpls/',

and tmpls/  in test.js

**Comment by eleazan** [comment]
You still without tmpl_path...

That is in your test.js file:
```javascript
var calendar = $('#calendar').calendar({
    events_source: [
        {
            "id": 293,
            "title": "Event 1",
            "url": "http://example.com",
            "class": "event-important",
            "start": 1463553900000, // Milliseconds
            "end": 1463561100000 // Milliseconds
        },
       
    ]});
```

And, if you don't provide a tmpl_path, it asume that is that: http://one2teach.com/tmpls/ and you are modifyng that: http://one2teach.com/bootstrap-calendar-master/tmpls/.

So, you can edit the ROOT/tmpls/day.html and set the link (that version is diferent from github!), or change the tmpl_path with the correct:
```javascript
var calendar = $('#calendar').calendar({
    tmpl_path: 'bootstrap-calendar-master/tmpls/',
    events_source: [
        {
            "id": 293,
            "title": "Event 1",
            "url": "http://example.com",
            "class": "event-important",
            "start": 1463553900000, // Milliseconds
            "end": 1463561100000 // Milliseconds
        },
       
    ]});
```

I hope that can help you!

**Comment by mmguide2003** [comment]
Yes,I had an epiphany on that one last, realising the 'tmpls' path was relative to the main calendar url. Thanks very much for all your help.
