### ISSUE TITLE
bootstrap-calendar not working in a flask project

### ISSUE THREAD

**Issue by waqaralidetho** [Serhioromano/bootstrap-calendar#620]
It is not an issue but a question. I am trying to use this calendar into my flask application, however the html file is running fine in isolation, but when I try to call this file from flask app it is not working. I cannot see the calendar. I can only see the bootstrap buttons of year month day and next previous etc. I also tried to call the java-script files according to flask's way of calling static files, but it also did not work. Any suggestions would be very appreciated.

**Comment by dandruff123** [comment]
I will tell you from my experience, because you have to figure out how the calendar works. Don't know anything about flask, but know that you must have mixed the order of the js files loading. They must be in order 
```
<script type="text/javascript" src="js/vendor/jquery-1.9.1.js"></script>
**<script type="text/javascript" src="js/vendor/bootstrap.min.js"></script>**
<script type="text/javascript" src="js/vendor/underscore-min.js"></script>
<script type="text/javascript" src="js/calendar.js"></script>
<script type="text/javascript">
   var calendar = $("#calendar").calendar(
   {   tmpl_path: "/tmpls/",
       events_source: function () { return []; }
   });
</script>
```
Not sure if you've included bootstrap.js file, which basically is **not** included in the basic docs of this repository. At least that helped me.

**Comment by waqaralidetho** [comment]
Hi dandruff, thank you for your reply. As far as I understood, From somewhere inside the calendar code it is calling files from tmpls and it is requesting for a wrong path. For example Flask only allow you to get files from a static folder if a request comes for another folder Flask does not allow accessing that file. Now what is happening all the files (js) files have been loaded but from somewhere inside the code it is requesting for tmpls 'month.html' file. I am getting the following error in my console of browser

jquery.min.js:4GET http://127.0.0.1:5000/verifyDomain/tmpls/month.html?_=1463436714276 404 (NOT FOUND)

Actually my static path is 

http://127.0.0.1:5000/pdf/tmpls/month.html

Now I do not know how to change the tmpls path as the second one. If you have any idea of the code. Please tell me so. 

As far as bootstrap is concerned I can see bootstrap styles in the form of buttons into my html. So I believe it is loading the bootstrap.

**Comment by dandruff123** [comment]
So in the beginning you set the default options for the calendar. They are often as follows:
```
var options = {
        events_source: '/events', //in this case url, but can put array or object for test cases
        view: 'month',
        tmpl_path: 'tmpls/',
        tmpl_cache: false,
        day: '2016-05-18'
        ....
}
```
Try to play with  **tmpl_path** variable. Depending on the framework and language you use the application searches for the templates, sending also the timestamp in microseconds for the moment of the request (in your case 1463436714276 / delete 276 and you get 05/16/2016 10:11pm (UTC)). I had to put tmpls folder in the root folder, some software would look in the folder where calendar.js is placed, rarely where your framework or language would search for. Also, try using **Firefox** instead of Chrome, which will allow your local files to load. Once on a server browsers will work the same way.
These are just some suggestions that you can try. Bootstrap **JS** (not CSS) has little or nothing to do with you buttons by the way, but is used for the calendar.

**Comment by eleazan** [comment]
You need to set `tmpl_path: '/pdf/tmpls/'`

**Comment by waqaralidetho** [comment]
Hi guys, 

thank you so much I am able to use this calendar with your help in flask. I changed `tmpl_path: '/pdf/tmpls/' ` in `calendar.js` and `app.js` file. Also I set ` events_source: '/pdf/events.json.php'`, in `app.js `file. My html file looks as follow for someone else trying to use flask. 


```
<link rel="stylesheet" href="/pdf/components/bootstrap2/css/bootstrap.css">
	<link rel="stylesheet" href="/pdf/components/bootstrap2/css/bootstrap-responsive.css">
	<link rel="stylesheet" href="/pdf/css/calendar.css">

	<style type="text/css">
		.btn-twitter {
			padding-left: 30px;
			background: rgba(0, 0, 0, 0) url(https://platform.twitter.com/widgets/images/btn.27237bab4db188ca749164efd38861b0.png) -20px 6px no-repeat;
			background-position: -20px 11px !important;
		}
		.btn-twitter:hover {
			background-position:  -20px -18px !important;
		}
	</style>
</head>
<body>
<div class="container">

	<div class="page-header">

		<div class="pull-right form-inline">
			<div class="btn-group">
				<button class="btn btn-primary" data-calendar-nav="prev"><< Prev</button>
				<button class="btn" data-calendar-nav="today">Today</button>
				<button class="btn btn-primary" data-calendar-nav="next">Next >></button>
			</div>
			<div class="btn-group">
				<button class="btn btn-warning" data-calendar-view="year">Year</button>
				<button class="btn btn-warning active" data-calendar-view="month">Month</button>
				<button class="btn btn-warning" data-calendar-view="week">Week</button>
				<button class="btn btn-warning" data-calendar-view="day">Day</button>
			</div>
		</div>

		<h3></h3>

	</div>

	<div class="row">
		<div class="span9">
			<div id="calendar"></div>
		</div>

	</div>
    <!-- place to add new code -->

	<script type="text/javascript" src="/pdf/components/jquery/jquery.min.js" cache="no"></script>
	<script type="text/javascript" src="/pdf/components/bootstrap2/js/bootstrap.min.js" cache="no"></script>
    <script type="text/javascript" src="/pdf/components/underscore/underscore-min.js" cache="no"></script>
	<script type="text/javascript" src="/pdf/js/calendar.min.js" cache="no"></script>
	<script type="text/javascript" src="/pdf/js/app.js" cache="no"></script>
	<script type="text/javascript">
       var calendar = $("#calendar").calendar(
       {
       		tmpl_path: "/pdf/tmpls/",
          	events_source: function () { return []; }
       });
    </script>
</div>
```
```
