### ISSUE TITLE
Day View - Display events horizatally 

### ISSUE THREAD

**Issue by nishadotcom** [Serhioromano/bootstrap-calendar#623]
Hai,

when more events are loaded to the day view, after aout 5 or 6 records  the reaming records moved to the bottom of day view calendar.

And I have the following issue.

Please check the attachemnt.

![smi-cal](https://cloud.githubusercontent.com/assets/15242739/15566097/9da231b0-233c-11e6-96be-09e322bdaa33.png)

Best
nishadotcom

**Comment by eleazan** [comment]
Any public url? :)

**Comment by nishadotcom** [comment]
Hai @eleazan 

Sorry, Currently, I do not have any public url. 

Do you get my problem????

Please suggest.

Best,
nishadotcom

**Comment by eleazan** [comment]
@nishadotcom 

Maybe, you can do something like: 
```
#cal-day-box .day-event {  position: absolute; }
```
And then, add a margin-left like 200*nº event on that hour, for avoid the overlap effect

**Comment by nishadotcom** [comment]
Hai @eleazan ,

Thank You. I have sorted it by getting events.

Thank You

Best,
nishadotcom
