### ISSUE TITLE
Get Events Base By - Hour in day view

### ISSUE THREAD

**Issue by nishadotcom** [Serhioromano/bootstrap-calendar#625]
Hai,

Could you please tell how to get the events by the given Hour????

Ex. I need to get 12 PM events.

Please suggest.

Best,
nishadotcom

**Comment by eleazan** [comment]
How do you get your events? 

If you get by json, you can add a parameter to only fetch certain time

**Comment by nishadotcom** [comment]
Thank You @eleazan 

I have sorted my issue.

Best,
nishadotcom
