### ISSUE TITLE
Display Problem (Flask)

### ISSUE THREAD

**Issue by roddajohn** [Serhioromano/bootstrap-calendar#626]
Hello,

Excuse my lack of knowledge, but this project is really quite great, and I would really like to get it working in my Flask app.

Currently, when I display the page, it looks something like this: 
![screen shot 2016-05-31 at 6 33 06 pm](https://cloud.githubusercontent.com/assets/10851328/15692739/34dd420c-275e-11e6-8e58-8e004c8b4ffa.png)

This is clearly not the pretty bootstrap which I want to see :)  However, if you hover over the long number of the right, it will change to something like this:
![screen shot 2016-05-31 at 6 34 19 pm](https://cloud.githubusercontent.com/assets/10851328/15692773/5c04f0f0-275e-11e6-9b99-b313bc67dfb6.png)

You can also click on random things, and change the view to something like this:
![screen shot 2016-05-31 at 6 35 08 pm](https://cloud.githubusercontent.com/assets/10851328/15692782/6dc1af0e-275e-11e6-8cbd-2eb56b9f3c25.png)

This makes me think that the backend is working correctly, and there is just an issue with the viewing / bootstrap, which leads me to my include statements.

```
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
<link rel="styleshoot" href="{{ url_for('static', filename='css/calendar.css') }}"
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/underscore-min.js') }}"></script>
<script src="{{ url_for('static', filename='js/calendar.js') }}"></script>
```

The bootstrap includes I know are working because I use them at other points in the project and everything works fine (modals, buttons, etc, you name it, it works).  

JQuery is throwing a warning in the console which I don't know if it is related or not, but I will post it anyways: 
`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/`

The code related to the calendar in the html file is:  
```
<div id="calendar"></div>

  <script type="text/javascript">
    var calendar = $("#calendar").calendar(
    {
    tmpl_path: "/static/tmpls/",
    events_source: function () { return []; }
    });
  </script>
```

Any help would be much appreciated!

**Comment by eleazan** [comment]
it's fixed, really?

i think is a issue with css's ;)

**Comment by roddajohn** [comment]
Yes, I fixed it.  I had misspelled stylesheet!

A perfect example of how a typo can destroy everything, it is working wonderfully now!

Thanks for the project
