### ISSUE TITLE
How can I implement repeat event feature?

### ISSUE THREAD

**Issue by sagarhspl** [Serhioromano/bootstrap-calendar#635]
I want to implement repeat feature in bootstrap calendar, i.e. every day, every week, every month, every year etc.
Is there any solution on this?

**Comment by eleazan** [comment]
Set it on your php / json file o.O

**Comment by sagarhspl** [comment]
@eleazan 
Thanks for your reply.. but how..? can I create dummy events for recurring  ?

**Comment by eleazan** [comment]
Uhm, on the get request for events, you get start and end...

You can do something like

```
current = start;
while( current < end) {
 if(current % start == 7) {
   // For repeat every week
    events[] = array("start" => current, "end" => current+1hour)
 }
 current += 1 day;
}
```

It's not a functional code.. but maybe give you an idea :)

**Comment by sagarhspl** [comment]
@eleazan 
thanks for the prompt reply and suggestion I will implement this way..
