### ISSUE TITLE
Get events that are currently shown in calendar

### ISSUE THREAD

**Issue by ArunoDh** [Serhioromano/bootstrap-calendar#638]
Hello guys

so i'm currently working on this project where i need to show events in a calendar and in tiles. 
Everything from this calendar is working but i wonder if there is any way to get the elements that are currently shown.
So what i mean is: you select a week, in this week are 3 events. Can i get these 3 events? 
I can then use those objects to create the tiles. 

Thanks in advance
Aruno

**Comment by eleazan** [comment]
You can expose the calendar var, and get it on

```
calendar.options.events
```

**Comment by ArunoDh** [comment]
Thanks Eleazan!

**Comment by jack1535** [comment]
Sorry, still don't understand how it work. Could you provide more detail?

**Comment by EzequielGv83** [comment]
Expose the calendar variable and then options.position.start or end.

**Comment by EzequielGv83** [comment]
> Sorry, still don't understand how it work. Could you provide more detail?

Consider that your calendar is initialized like this

 var **calendar** = $('#calendar').calendar(options);

 function return_events(){
    var events_array = **calendar**.options.events;

    $.each(events_array, function(k, v) {
        console.log(k);
        console.log(v);
    });
    }
