### ISSUE TITLE
target _blank issues 

### ISSUE THREAD

**Issue by lucastsirex** [Serhioromano/bootstrap-calendar#643]
Hi, there is a way to set the links of the events inside the calendar in target _black??
thx

**Comment by avilac3** [comment]
nice idea

**Comment by lucastsirex** [comment]
i find the answer. I modified the html in the tmpls folders.

**Comment by avilac3** [comment]
please post the code templete

**Comment by eleazan** [comment]
You only need add attribute target to a elements: 

https://github.com/Serhioromano/bootstrap-calendar/blob/master/tmpls/month-day.html#L6 for example
