### ISSUE TITLE
When select next month, localization is lost

### ISSUE THREAD

**Issue by widonwaker** [Serhioromano/bootstrap-calendar#657]
As title says, when i switch "next>>" or "<<prev" month, it comes back the default localization (i've et it to italian and it loads in italian, except the month name, it stays english, why? ) but when i switch month, all days return in english. How can i fix this?

**Comment by eleazan** [comment]
How do you init the navs buttons?

**Comment by widonwaker** [comment]
problem solved, i had the change the localization in javascript file too.

**Comment by cometin111** [comment]
How did you solve it?? XD

**Comment by eleazan** [comment]
@cometin111, be sure that you dont reinit all the calendar on month change... see the demo page ( you can see here: [demo](http://bootstrap-calendar.eivissapp.com/) ) you can change the month without change the localization
