### ISSUE TITLE
click Prev or Next button ,just refresh the page and don't switch to prev/next month??

### ISSUE THREAD

**Issue by xlkit456852** [Serhioromano/bootstrap-calendar#658]
I can see the calendar .But when I click Prev or Next button , I just got a page and don't switch to prev/next month??
code:
var calendar = $('#calendar').calendar({
            events_source: function(){return [
                ''
            ];},
            tmpl_path: '{{url('static')}}/calendar-tmpls/',
            language : 'zh-CN'
        });

**Comment by widonwaker** [comment]
have you loaded app.js?

**Comment by cometin111** [comment]
It could be fixed? XD

**Comment by eleazan** [comment]
See app.js for more info >-<
