### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by guillermovil** [Serhioromano/bootstrap-calendar#660]
It is a great tool!! Thank you very much! where I can find documentation?

**Comment by mikemimik** [comment]
Most of the documentation for this library is in the [README file](https://github.com/Serhioromano/bootstrap-calendar/blob/master/README.md). Any other information you need to gleen from the [source code](https://github.com/Serhioromano/bootstrap-calendar/blob/master/js/calendar.js) itself.

**Comment by eleazan** [comment]
Yo have a little [wiki ](https://github.com/Serhioromano/bootstrap-calendar/wiki) too
