### ISSUE TITLE
Why isn't the current date loading when the page loads

### ISSUE THREAD

**Issue by 1EyeTy** [Serhioromano/bootstrap-calendar#662]
I put the minimum needed example on my page and it keeps coming up to the March 2013 date. How in the heck do I reset that and clear out the test event?

Thanks

Ty

**Comment by joshreade** [comment]
Open app.js and comment out the line:-   day: "2016-09-26". The calendar will then load today's date.

**Comment by 1EyeTy** [comment]
Thanks Joshreade!
