### ISSUE TITLE
DEMO NOT WORKING

### ISSUE THREAD

**Issue by Fabiosalbuquerque** [Serhioromano/bootstrap-calendar#665]
Fix Demo please

**Comment by RicardoSaracino** [comment]
Having the same issue both Bootstrap2 and 3

**Comment by peshmerge** [comment]
I have the same issue. I have tested it on the following browsers (Chrome, FireFox, IE, Vivaldi, Opera) and still doesn't work!

**Comment by criztovyl** [comment]
#663

**Comment by peshmerge** [comment]
Omg! And it's merged! WTH!

**Comment by criztovyl** [comment]
https://github.com/Serhioromano/bootstrap-calendar/issues/664#issuecomment-250334162

**Comment by dattz** [comment]
Can we fix it sooner please?

**Comment by aguillem** [comment]
Sorry, i fix it and submit new pull request #667

**Comment by Serhioromano** [comment]
> DEMO NOT WORKING

I had my demo site hosted on Azure. The free 10 websites subscription is over now and all my websites are gone. I am thinking of moving demo site to AWS S3.

But most probably you mean that local demo not woking as well.

**Comment by RicardoSaracino** [comment]
im in aws, about 15$ / month
