### ISSUE TITLE
First day monday by default

### ISSUE THREAD

**Issue by t3loki** [Serhioromano/bootstrap-calendar#677]
Hello, 

How to disable sunday first day completely and leave only monday ? So that when the calendar opens, shows monday as the first day by default.

Thanks

**Comment by mikemimik** [comment]
If you fork the project and change the internal `defaults_extended.first_day` to `1` then monday will be the first day of the week.

Source code: https://github.com/Serhioromano/bootstrap-calendar/blob/master/js/calendar.js#L170

**Comment by eleazan** [comment]
Or add first_day to 1 on init calendar...
