### ISSUE TITLE
release demo doesn't work

### ISSUE THREAD

**Issue by Anton-Strygin** [Serhioromano/bootstrap-calendar#679]
Downloaded the latest release sources, tried to open index-bs3.html in browser. Calendar is not shown. In console I can see 4 errors and 1 warning (screenshot attached). Where I can get fixed version?
![image](https://cloud.githubusercontent.com/assets/2479518/19959008/6e0dc710-a1b4-11e6-9862-1cdcc7a4eb4e.png)

**Comment by eleazan** [comment]
On home page (github), you have that:

> Usage warning.

> You cannot use the calendar from a local file. The following error will be displayed : Failed to load resource: Origin null is not allowed by Access-Control-Allow-Origin.

>Using Ajax with local resources (file:///), is not permited. You will need to deploy this to the web instead.
