### ISSUE TITLE
How I can to use the calendar only on an annual basis ( Yearly ) ? 

### ISSUE THREAD

**Issue by fatihBulbul** [Serhioromano/bootstrap-calendar#680]
How I can to use the calendar only on an annual basis ( Yearly ) ?  I don’t want to use the other formats on calender.

**Comment by eleazan** [comment]
With two options:

view: for select the initial view (year)
and "views", an array that you can enable / disable views

```
views: {
			year: {
				slide_events: 1,
				enable: 1
			},
			month: {
				slide_events: 1,
				enable: 0
			},
			week: {
				enable: 0
			},
			day: {
				enable: 0
			}
		},
```

**Comment by fatihBulbul** [comment]
thank you :)
