### ISSUE TITLE
Demo Error

### ISSUE THREAD

**Issue by ajalexsmith** [Serhioromano/bootstrap-calendar#684]
Getting multiple errors resulting in the calendar not being displayed. Any idea's? 
![image](https://cloud.githubusercontent.com/assets/20641033/20052620/b06f0ec8-a4cc-11e6-9ed5-b06c8144bc15.png)

**Comment by nachille** [comment]
Hi, as said in the [Usage warning](https://github.com/Serhioromano/bootstrap-calendar/blob/master/README.md#usage-warning) section:

> You cannot use the calendar from a local file. The following error will be displayed : Failed to load resource: Origin null is not allowed by Access-Control-Allow-Origin.
> 
> Using Ajax with local resources (file:///), is not permited. You will need to deploy this to the web instead.

**Comment by gretschann** [comment]
Online version on http://bootstrap-calendar.azurewebsites.net/ is not avalable too

> Failed to load resource: net::ERR_NAME_NOT_RESOLVED

**Comment by Nerian** [comment]
@gretschann I get a 404 in the online version

**Comment by huphtur** [comment]
Demo site DNS address could not be found. 😢

**Comment by DimasInchidi** [comment]
+1 for demo site couldn't be found

**Comment by Nmaster88** [comment]
IS this going to get fixed?

**Comment by eleazan** [comment]
I contact to @Serhioromano for that...

**Comment by eleazan** [comment]
Waiting for response, meanwhile, you have demo here: http://bootstrap-calendar.eivissapp.com/
