### ISSUE TITLE
Time is incorrect - Please point me to the right file if I need to edit anything.

### ISSUE THREAD

**Issue by ErikThiart** [Serhioromano/bootstrap-calendar#687]
Hi, 
I wrote the php form to add events and that appears to be working very nice see json response below:

**This is what my json looks like:**

```
{  
   "success":1,
   "result":[  
      {  
         "id":"2",
         "title":"Booked",
         "url":"No Url",
         "start":"1479094200000",
         "end":"1479097800000"
      },
      {  
         "id":"3",
         "title":"Booked",
         "url":"No Url",
         "start":"1479103200000",
         "end":"1479108600000"
      }
   ]
}
```

However my Calendar appears to end short each time. I am in a GMT+2:00 zone if that helps ( Africa/Johannesburg) 

**See screenshot below:**

![2016-11-14_12-44-55](https://cloud.githubusercontent.com/assets/9626641/20261846/4ca461c6-aa68-11e6-9ecb-9537deb81f90.jpg)

**Comment by kristianharmer** [comment]
Hi ErikThiart,

This appears to be working fine. I thought the same at first glance but you can see that the label for 6:30 comes after the line that marks that moment in time! So the yellow mark you added is actually 6:30+.

K...

**Comment by ErikThiart** [comment]
Aha, I hear you, so I will just play around add some padding and make it visually more apparent.
