### ISSUE TITLE
No Calendar is displayed in Chrome and IE(It's only working in Firefox) 

### ISSUE THREAD

**Issue by Aravind13** [Serhioromano/bootstrap-calendar#692]
I downloaded the zip and tried to open the index.html, In Mozilla everything is working fine but in IE and Chrome there is no display of calendar

**Comment by Aravind13** [comment]
XMLHttpRequest cannot load file:///C:/Users/AB53419/Desktop/bootstrap-calendar-master/bootstrap-calend…00&utc_offset_from=420&utc_offset_to=360&browser_timezone=America%2FDenver. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
send @ jquery.min.js:4
ajax @ jquery.min.js:4
loader @ calendar.js:966
(anonymous) @ calendar.js:990
onBeforeEventsLoad @ calendar.js:145
Calendar._loadEvents @ calendar.js:988
Calendar.view @ calendar.js:785
Calendar @ calendar.js:401
$.fn.calendar @ calendar.js:1300
(anonymous) @ app.js:36
(anonymous) @ app.js:87
jquery.min.js:4 XMLHttpRequest cannot load file:///C:/Users/AB53419/Desktop/bootstrap-calendar-master/bootstrap-calendar-master/tmpls/month.html?_=1481233366582. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
send @ jquery.min.js:4
ajax @ jquery.min.js:4
Calendar._loadTemplate @ calendar.js:1018
Calendar._render @ calendar.js:427
Calendar.view @ calendar.js:786
Calendar @ calendar.js:401
$.fn.calendar @ calendar.js:1300
(anonymous) @ app.js:36
(anonymous) @ app.js:87
calendar.js:461 Uncaught TypeError: this.options.templates[this.options.view] is not a function
    at Calendar._render (calendar.js:461)
    at Calendar.view (calendar.js:786)
    at new Calendar (calendar.js:401)
    at n.fn.init.$.fn.calendar (calendar.js:1300)
    at app.js:36
    at app.js:87
Calendar._render @ calendar.js:461
Calendar.view @ calendar.js:786
Calendar @ calendar.js:401
$.fn.calendar @ calendar.js:1300
(anonymous) @ app.js:36
(anonymous) @ app.js:87
index-bs3.html:171 GET file://bootstrapcalendar.disqus.com/embed.js net::ERR_FILE_NOT_FOUND

**Comment by Aravind13** [comment]
The above are the errors in console

**Comment by rbubley** [comment]
@Aravind13, Is this just as per the Usage Warning in the Readme?
