### ISSUE TITLE
Demo link seems to be broken

### ISSUE THREAD

**Issue by caneta** [Serhioromano/bootstrap-calendar#693]
I cannot reach the demo...

**Comment by Luitame** [comment]
@caneta you can clone the project and run in your localhost. I did it!

**Comment by caneta** [comment]
Well, ok, but this is not the point...I would only notify about an annoying broken link.

**Comment by Luitame** [comment]
I sent a email to project creator talking about this.

**Comment by eleazan** [comment]
@Luitame any response? I have host the demo page here http://bootstrap-calendar.eivissapp.com/

**Comment by Luitame** [comment]
@eleazan that's right. Now it's functioning. Please, change link in project home page.

**Comment by eleazan** [comment]
@Luitame i can't :(

**Comment by Serhioromano** [comment]
I have updated description with new link.
