### ISSUE TITLE
Demo Link is Dead

### ISSUE THREAD

**Issue by frogydiak** [Serhioromano/bootstrap-calendar#699]
The demo link goes to a dead site.

**Comment by Nmaster88** [comment]
Is this going to get fixed?

**Comment by rtsmith** [comment]
check here: https://mattlewis92.github.io/angular-bootstrap-calendar

**Comment by Nmaster88** [comment]
Thanks, but isn't that with angular? i was looking for the jquery version. I think i've found a working link here: http://www.columbia.edu/cu/questscholars/calendar.html

**Comment by eleazan** [comment]
Here is too (hosted by me) http://bootstrap-calendar.eivissapp.com/
