### ISSUE TITLE
Update calendar view (pull events again)

### ISSUE THREAD

**Issue by mschutze** [Serhioromano/bootstrap-calendar#702]
Hello,
First of all, great work on the Calendar!
I'm looking for a way to update the calendar events for the current view after closing the modal window. Is there a way to do that?
The idea is that the user can edit an event on the php page in the modal window, and after closing it, can see the updated event in the calendar. Currently, the has to reload the page and navigate to the month again...
Thanks,

**Comment by eleazan** [comment]
You can do ```calendar.view()```

**Comment by mschutze** [comment]
Thanks!
I added calendar.view('month') to this section in calendar.js:
`.on('hidden.bs.modal', function() {
	self.options.onAfterModalHidden.call(self, self.options.events);
	calendar.view('month');
})`
After closing the modal window the calendar gets updated with the updated event.

**Comment by eleazan** [comment]
@mschutze Not need the month arg... it get the current view ;)
