### ISSUE TITLE
da-DK version miss-spells March in Danish

### ISSUE THREAD

**Issue by xidus** [Serhioromano/bootstrap-calendar#706]
I am using the calendar in Danish (da-DK) and noticed that March is spelled wrong.

In `/js/language/da-DK.js` the line following line:

```json
	m2: 'Marst',
```

should instead be

```json
	m2: 'Marts',
```

**Comment by MaXFalstein** [comment]
Create a PR for it.

**Comment by xidus** [comment]
I shall, when I am on a machine with access to Git.

**Comment by Serhioromano** [comment]
Your #707 was accepted.
