### ISSUE TITLE
get the date after navigation

### ISSUE THREAD

**Issue by Alkaendra** [Serhioromano/bootstrap-calendar#708]
I know, I'm sure its very easy but I have a great headache by now...

I need to pass the real date to php, in the day view, after use the next or previous navigation buttons.
I mean, when you select a day, see the hours panel and if you get the date, you obtain the actual date. But if you navigates, the date taken is the first one not the ACTUAL one AFTER navigation, and I need it.

It is possible?

**Comment by Alkaendra** [comment]
Ok. Confirmed. It was easy after all, and me stupid :dagger: 
Sorry for bothering you.

**Comment by EzequielGv83** [comment]
So, what you did?

I want to get the current from and to request another stand alone calendar (only monthly events).

source(self.options.position.start, self.options.position.end)

**Comment by cablegunmaster** [comment]
Please open a new ticket and give waaay more details on what you are trying to accomplish explain why a “seperate” calendar is needed etc. 

This ticket is closed.
