### ISSUE TITLE
Fix URL in project description on GitHub

### ISSUE THREAD

**Issue by niftylettuce** [Serhioromano/bootstrap-calendar#709]
@Serhioromano please go to https://github.com/Serhioromano/bootstrap-calendar when you are logged into GitHub and fix the URL for the project to point to the demo at http://bootstrap-calendar.eivissapp.com/ - thanks!

**Comment by johnMinelli** [comment]
what are the credeintals for the demo?

**Comment by eleazan** [comment]
> what are the credentials for the demo?

You don't need credentials. That was a error server on my side! Try again :-)
