### ISSUE TITLE
Successful event load, but can not see in calendar

### ISSUE THREAD

**Issue by wynnbeattie** [Serhioromano/bootstrap-calendar#713]
using php7, and download from 3-31.
	$data = date('2013-03-22 08:00');
	$data1 = date('2013-03-22 09:00');
	echo  " ".date('Y m d H:i:s',strtotime($data));
	//exit;
	
	$out[] = array(
     	'id' => 777,
		'title' => 'Test 1',
		'url' => 'example.com',
		'class' => 'event-important',
		'start' => strtotime($data).'000',
		'end' => strtotime($data1).'000'
	);
returns:
Time=1490968161 2013 03 22 08:00:00{"success":1,"result":[{"id":777,"title":"TEST ","url":"example.com","class":"event-important","start":"1363939200000","end":"1363942800000"}]} 

I can verity the unix timestamp to 3-22-3013 where the other events are, but I am unble to locate it on the calendar for 3-22 or any other event. Does the above look ok ?

**Comment by wynnbeattie** [comment]
Thanks for the tip. I will work it that way...
Cheers,
Wynn

**Comment by Serhioromano** [comment]
Also not you set year 2013, so you should navigate to those dates. I am sure you know that but sometimes people miss this.
