### ISSUE TITLE
Support for Bootstrap 4

### ISSUE THREAD

**Issue by editicalu** [Serhioromano/bootstrap-calendar#742]
Bootstrap 4 has been released. Will this project support it or is it supported now?

**Comment by eleazan** [comment]
I think it's not hard to do it!

**Comment by Serhioromano** [comment]
Calendar is based on templates. You can open templates folder and edit HTML separately from JS. 

I do not plan to update it to BS4 if only someone else send a PR.

**Comment by dalenewman** [comment]
For anyone distressed about the absence of Bootstrap 4.  I updated my [templates](https://github.com/dalenewman/OrchardCore.Transformalize/tree/master/src/OrchardCore.Transformalize/wwwroot/Scripts/tmpls) without too much trouble.
