### ISSUE TITLE
Week view: incorrect postition 

### ISSUE THREAD

**Issue by nealweston** [Serhioromano/bootstrap-calendar#764]
Hi,

I have been using and modifying this calendar for my needs for quite some time now, and it is almost perfect. Except that week template displays events underneath each other (for an example: Monday starts at the correct position at the top of the column, however Tuesday starts below Monday (although in its separate column). Picture below my post will illustrate what I'm trying to accomplish.

I have tried editing css, but with no luck. I'm not using any custom CSS at this time. Has someone fixed this problem?

![calweek](https://user-images.githubusercontent.com/49947140/56658778-23a20080-66a4-11e9-9a6c-8ac0ef291708.png)

**Comment by tinozh** [comment]
Hi, you have closed this - have you found a solution for this?

**Comment by nealweston** [comment]
> Hi, you have closed this - have you found a solution for this?

Kind of, I basically redid the week-days.html using bootstrap columns and start_days. Its not the most optimal solution for sure, but fast enough for me. 
I used if statements [if (event.start_day == 0)] through [if (event.start_day == 6)]. I also edited the css file, can't really remember which line, but you'll need to set column widths and so on, easy enough.

<div class="col-md-1 cal-width">
   <% _.each(events, function(event){
      if (event.start_day==0) { %> 
   <div class="cal-row-fluid">
      <div class="col-md-1 cal-cell<%= event.days%> day-highlight dh-<%= event['class'] %>" data-event-class="<%= event['class'] %>">
         <a href="<%= event.url ? event.url : 'javascript:void(0)' %>" data-event-id="<%= event.id %>" class="cal-event-week event<%= event.id %>"><%= event.title %></a>
      </div>
   </div>
   <% 
      }}); %>
</div>



also in week.html I added div class="col-md-1" to the div inside each-loop like this
`<div class="col-md-1  cal-cell1 <%= cal._getDayClass('week', start) %>" data-toggle="tooltip" title= .........>`

**Comment by Toomas633** [comment]
Any updates on where or what in the css should i change.
