### ISSUE TITLE
Need Month View With Resource (Room Detail like Day View)

### ISSUE THREAD

**Issue by UzairAshraf123** [Serhioromano/bootstrap-calendar#765]
I want Month View like Day View but there should be Date instead of Time.
![image](https://user-images.githubusercontent.com/23142309/59561623-fc303a00-903b-11e9-9b59-9ccc540ed1fa.png)

**Comment by cablegunmaster** [comment]
Okay, please elaborate your question. 
"There should be date instead of time" Where?

Please post a screenshot with your "desired" endresult 'mspaint' as for now your question seems unclear to what you want to be changed.

**Comment by UzairAshraf123** [comment]
![image](https://user-images.githubusercontent.com/23142309/59616724-7517ba80-913e-11e9-8c66-26b408b96c80.png)


i want view like this: 
![image](https://user-images.githubusercontent.com/23142309/59616767-852f9a00-913e-11e9-878f-82ac9b2617d5.png)

**Comment by UzairAshraf123** [comment]
please reply me as soon as possilbe.
Thanks

**Comment by cablegunmaster** [comment]
this seems like a template issue, custom made issue not a general library one.
this requires a rewrite with a new different type of template.
It can be done and I estimate it requires 2-3 days (8-10 hours of figuring everything out ) 
of fitting its not easy to make.

**Comment by eleazan** [comment]
The views are templates.. feel free to do your own template... and maybe you can share with us! 

Thats not an issue, but anthing, we can help!
